/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CopiaSeguridad.file;

import ListDatos.JFilaDatosDefecto;
import java.io.File;
import javax.swing.JFileChooser;
import main.JDatosGeneralesP;
import utiles.JDepuracion;
import utilesGUIx.JGUIxConfigGlobal;
import utilesGUIx.controlProcesos.JProcesoAccionAbstracX;
import utilesGUIx.formsGenericos.JMostrarPantalla;
import utilesGUIx.msgbox.JMsgBox;

/**
 *
 * @author eduardo
 */
public class JPanelQuitarCaracteresRaros extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCopiaSeguridad
     */
    public JPanelQuitarCaracteresRaros() {
        initComponents();
        jTextFieldCZ1.setValueTabla(JQuitarCaracteresRaros.mcsPatron);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel25 = new javax.swing.JPanel();
        jLabelCZ27 = new utilesGUIx.JLabelCZ();
        txtRutaOrigen = new utilesGUIx.JTextFieldCZ();
        btnExplorarOrigen = new utilesGUIx.JButtonCZ();
        jLabelCZ2 = new utilesGUIx.JLabelCZ();
        jTextFieldCZ1 = new utilesGUIx.JTextFieldCZ();
        jButtonCZ1 = new utilesGUIx.JButtonCZ();
        jButtonCZ2 = new utilesGUIx.JButtonCZ();

        setLayout(new java.awt.GridBagLayout());

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta origen"));
        jPanel25.setLayout(new java.awt.GridBagLayout());

        jLabelCZ27.setText("ruta");
        jPanel25.add(jLabelCZ27, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel25.add(txtRutaOrigen, gridBagConstraints);

        btnExplorarOrigen.setText("...");
        btnExplorarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarOrigenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel25.add(btnExplorarOrigen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanel25, gridBagConstraints);

        jLabelCZ2.setText("<html>Patron: secuencia de 2 caracteres <br> 1º caracter el buscar para sustituir <br> 2º caracter el que sustituye</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabelCZ2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldCZ1, gridBagConstraints);

        jButtonCZ1.setText("Aceptar");
        jButtonCZ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCZ1ActionPerformed(evt);
            }
        });
        add(jButtonCZ1, new java.awt.GridBagConstraints());

        jButtonCZ2.setText("Cancelar");
        jButtonCZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCZ2ActionPerformed(evt);
            }
        });
        add(jButtonCZ2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnExplorarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarOrigenActionPerformed
        File loFile = null;
        try{
            JFileChooser loFileM = new JFileChooser();
            loFileM.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if(loFileM.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                loFile = loFileM.getSelectedFile();
                txtRutaOrigen.setText(loFile.getAbsolutePath());
            }
        }catch(Exception e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
    }//GEN-LAST:event_btnExplorarOrigenActionPerformed

    private void jButtonCZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCZ2ActionPerformed
        
        JGUIxConfigGlobal.getInstancia().getMostrarPantalla().cerrarForm(this);
        
    }//GEN-LAST:event_jButtonCZ2ActionPerformed

    private void jButtonCZ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCZ1ActionPerformed
        
        try{
           JDatosGeneralesP.getDatosGenerales().getThreadGroup().addProcesoYEjecutar(new JProcesoAccionAbstracX() {

                public String getTitulo() {
                    return "Quitar caracteres raros";
                }

                public int getNumeroRegistros() {
                    return -1;
                }

                public void procesar() throws Throwable {
                    JQuitarCaracteresRaros.main(new String[]{
                        txtRutaOrigen.getText() 
                        , jTextFieldCZ1.getText()

                    });
                }

                public String getTituloRegistroActual() {
                    return "";
                }

                public void mostrarMensaje(String psMensaje) {
                    JMsgBox.mensajeInformacion(null, psMensaje);
                }
            });
            
            JGUIxConfigGlobal.getInstancia().getMostrarPantalla().cerrarForm(this);
        }catch(Exception e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
        

    }//GEN-LAST:event_jButtonCZ1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnExplorarOrigen;
    private utilesGUIx.JButtonCZ jButtonCZ1;
    private utilesGUIx.JButtonCZ jButtonCZ2;
    private utilesGUIx.JLabelCZ jLabelCZ2;
    private utilesGUIx.JLabelCZ jLabelCZ27;
    private javax.swing.JPanel jPanel25;
    private utilesGUIx.JTextFieldCZ jTextFieldCZ1;
    private utilesGUIx.JTextFieldCZ txtRutaOrigen;
    // End of variables declaration//GEN-END:variables
}
