/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utilesGUIxAvisos.forms.util;

import ListDatos.JListDatos;
import javax.swing.JOptionPane;
import utiles.JDateEdu;
import utilesGUIx.msgbox.JMsgBox;
import utilesGUIxAvisos.consultas.JTFORMGUIXEVENTOS;
import utilesGUIxAvisos.tablasControladoras.JT2GUIXEVENTOS;


public class JPanelMES extends javax.swing.JPanel {
    private JDateEdu moFecha;
    private JDateEdu moHoy;
    private JPanelDIA[][] moDias = new JPanelDIA[6][7];
    private JT2GUIXEVENTOS moControlador;
    private JTFORMGUIXEVENTOS moEventos;

    /**
     * Creates new form JPanelMES
     */
    public JPanelMES() {
        initComponents();
        moDias[0][0] = jPanelDIA11;
        moDias[0][1] = jPanelDIA12;
        moDias[0][2] = jPanelDIA13;
        moDias[0][3] = jPanelDIA14;
        moDias[0][4] = jPanelDIA15;
        moDias[0][5] = jPanelDIA16;
        moDias[0][6] = jPanelDIA17;

        moDias[1][0] = jPanelDIA21;
        moDias[1][1] = jPanelDIA22;
        moDias[1][2] = jPanelDIA23;
        moDias[1][3] = jPanelDIA24;
        moDias[1][4] = jPanelDIA25;
        moDias[1][5] = jPanelDIA26;
        moDias[1][6] = jPanelDIA27;
        
        moDias[2][0] = jPanelDIA31;
        moDias[2][1] = jPanelDIA32;
        moDias[2][2] = jPanelDIA33;
        moDias[2][3] = jPanelDIA34;
        moDias[2][4] = jPanelDIA35;
        moDias[2][5] = jPanelDIA36;
        moDias[2][6] = jPanelDIA37;
        
        moDias[3][0] = jPanelDIA41;
        moDias[3][1] = jPanelDIA42;
        moDias[3][2] = jPanelDIA43;
        moDias[3][3] = jPanelDIA44;
        moDias[3][4] = jPanelDIA45;
        moDias[3][5] = jPanelDIA46;
        moDias[3][6] = jPanelDIA47;
        
        moDias[4][0] = jPanelDIA51;
        moDias[4][1] = jPanelDIA52;
        moDias[4][2] = jPanelDIA53;
        moDias[4][3] = jPanelDIA54;
        moDias[4][4] = jPanelDIA55;
        moDias[4][5] = jPanelDIA56;
        moDias[4][6] = jPanelDIA57;
        
        moDias[5][0] = jPanelDIA61;
        moDias[5][1] = jPanelDIA62;
        moDias[5][2] = jPanelDIA63;
        moDias[5][3] = jPanelDIA64;
        moDias[5][4] = jPanelDIA65;
        moDias[5][5] = jPanelDIA66;
        moDias[5][6] = jPanelDIA67;
        
        jPopupMenuEvento.add(jPanelver);
        for ( int i = 0; i < moDias.length; i++ ){
            for ( int ii = 0; ii < moDias[i].length; ii++ ){
                    moDias[i][ii].setPopUp(jPopupMenuEvento, jPanelver, jPanelTableRender1);
            }
        }        
        
    }
    
    public void setControlador(JT2GUIXEVENTOS poControlador) throws Exception{
        moControlador=poControlador;
        
    }
    public void setMes(int plAno, int plMes) throws Exception{
        moFecha = new JDateEdu(plAno, plMes, 1);
        moHoy=new JDateEdu();
        moHoy.setHora(0);
        moHoy.setMinuto(0);
        moHoy.setSegundo(0);
        recuperarDatosBD();
        rellenarMes();
        
        
    }
    protected void recuperarDatosBD() throws Exception {
        moEventos = (JTFORMGUIXEVENTOS) moControlador.getConsulta();
        JDateEdu loDate = (JDateEdu) moFecha.clone();
        loDate.setDia(loDate.mlDiasMesActual());
        moEventos.crearSelectFechas(moFecha.toString(), loDate.toString()); 
        moEventos.refrescar(false, false);
    }

    public void refrescarDias() throws Exception {
        rellenarMes();
    }

    private void rellenarMes() throws Exception{
        for ( int i = 0; i < moDias.length; i++ ){
            for ( int ii = 0; ii < moDias[i].length; ii++ ){
                    moDias[i][ii].setVisible(false);
            }
        }
        
        int lDiasMes = moFecha.mlDiasMesActual();
        JDateEdu loFechaAux = new JDateEdu();
        loFechaAux.setDate(moFecha.moDate());
        loFechaAux.setDia(1);
        loFechaAux.setHora(0);
        loFechaAux.setMinuto(0);
        loFechaAux.setSegundo(0);
        
        int lDiaSemana= loFechaAux.getDiaSemanaEspana();
        

        int lFila = 0;
        for ( int i = lDiaSemana; i < (lDiasMes+lDiaSemana); i++ )
        {
            loFechaAux.setDia(i+1-lDiaSemana);
            lFila = i / 7;
            JPanelDIA loDia = moDias[lFila][i % 7];
            
            loDia.setHoy(loFechaAux.compareTo(moHoy)==0 );
            loDia.setVisible(true);
            loDia.setModel((JDateEdu)loFechaAux.clone(),moEventos, moControlador);
        }   
//no vale        ((GridLayout)jPanelTodosDias.getLayout()).setRows(lFila);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelver = new javax.swing.JPanel();
        jPanelTableRender1 = new utilesGUIxAvisos.forms.util.JPanelTableRender();
        jPanel2 = new javax.swing.JPanel();
        jBtnEditar = new utilesGUIx.JButtonCZ();
        jBtnBorrar = new utilesGUIx.JButtonCZ();
        jButtonCancelar = new utilesGUIx.JButtonCZ();
        jPopupMenuEvento = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        jLabelCZ2 = new utilesGUIx.JLabelCZ();
        jLabelCZ3 = new utilesGUIx.JLabelCZ();
        jLabelCZ4 = new utilesGUIx.JLabelCZ();
        jLabelCZ5 = new utilesGUIx.JLabelCZ();
        jLabelCZ6 = new utilesGUIx.JLabelCZ();
        jLabelCZ7 = new utilesGUIx.JLabelCZ();
        jPanelTodosDias = new javax.swing.JPanel();
        jPanelDIA11 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA12 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA13 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA14 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA15 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA16 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA17 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA21 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA22 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA23 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA24 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA25 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA26 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA27 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA31 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA32 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA33 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA34 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA35 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA36 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA37 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA41 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA42 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA43 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA44 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA45 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA46 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA47 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA51 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA52 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA53 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA54 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA55 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA56 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA57 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA61 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA62 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA63 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA64 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA65 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA66 = new utilesGUIxAvisos.forms.util.JPanelDIA();
        jPanelDIA67 = new utilesGUIxAvisos.forms.util.JPanelDIA();

        jPanelver.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelver.add(jPanelTableRender1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/Edit16.gif"))); // NOI18N
        jBtnEditar.setText("Editar"); // NOI18N
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnEditar);

        jBtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/Delete16.gif"))); // NOI18N
        jBtnBorrar.setText("Borrar"); // NOI18N
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnBorrar);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/cancel.gif"))); // NOI18N
        jButtonCancelar.setText("Cancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanelver.add(jPanel2, gridBagConstraints);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 2, 2));

        jLabelCZ1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ1.setText("Lunes");
        jLabelCZ1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ1.setOpaque(true);
        jPanel1.add(jLabelCZ1);

        jLabelCZ2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ2.setText("Martes");
        jLabelCZ2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ2.setOpaque(true);
        jPanel1.add(jLabelCZ2);

        jLabelCZ3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ3.setText("Miercoles");
        jLabelCZ3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ3.setOpaque(true);
        jPanel1.add(jLabelCZ3);

        jLabelCZ4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ4.setText("Jueves");
        jLabelCZ4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ4.setOpaque(true);
        jPanel1.add(jLabelCZ4);

        jLabelCZ5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ5.setText("Viernes");
        jLabelCZ5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ5.setOpaque(true);
        jPanel1.add(jLabelCZ5);

        jLabelCZ6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ6.setText("Sabado");
        jLabelCZ6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ6.setOpaque(true);
        jPanel1.add(jLabelCZ6);

        jLabelCZ7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCZ7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCZ7.setText("Domingo");
        jLabelCZ7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCZ7.setOpaque(true);
        jPanel1.add(jLabelCZ7);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanelTodosDias.setLayout(new java.awt.GridLayout(0, 7));
        jPanelTodosDias.add(jPanelDIA11);
        jPanelTodosDias.add(jPanelDIA12);
        jPanelTodosDias.add(jPanelDIA13);
        jPanelTodosDias.add(jPanelDIA14);
        jPanelTodosDias.add(jPanelDIA15);
        jPanelTodosDias.add(jPanelDIA16);
        jPanelTodosDias.add(jPanelDIA17);
        jPanelTodosDias.add(jPanelDIA21);
        jPanelTodosDias.add(jPanelDIA22);
        jPanelTodosDias.add(jPanelDIA23);
        jPanelTodosDias.add(jPanelDIA24);
        jPanelTodosDias.add(jPanelDIA25);
        jPanelTodosDias.add(jPanelDIA26);
        jPanelTodosDias.add(jPanelDIA27);
        jPanelTodosDias.add(jPanelDIA31);
        jPanelTodosDias.add(jPanelDIA32);
        jPanelTodosDias.add(jPanelDIA33);
        jPanelTodosDias.add(jPanelDIA34);
        jPanelTodosDias.add(jPanelDIA35);
        jPanelTodosDias.add(jPanelDIA36);
        jPanelTodosDias.add(jPanelDIA37);
        jPanelTodosDias.add(jPanelDIA41);
        jPanelTodosDias.add(jPanelDIA42);
        jPanelTodosDias.add(jPanelDIA43);
        jPanelTodosDias.add(jPanelDIA44);
        jPanelTodosDias.add(jPanelDIA45);
        jPanelTodosDias.add(jPanelDIA46);
        jPanelTodosDias.add(jPanelDIA47);
        jPanelTodosDias.add(jPanelDIA51);
        jPanelTodosDias.add(jPanelDIA52);
        jPanelTodosDias.add(jPanelDIA53);
        jPanelTodosDias.add(jPanelDIA54);
        jPanelTodosDias.add(jPanelDIA55);
        jPanelTodosDias.add(jPanelDIA56);
        jPanelTodosDias.add(jPanelDIA57);
        jPanelTodosDias.add(jPanelDIA61);
        jPanelTodosDias.add(jPanelDIA62);
        jPanelTodosDias.add(jPanelDIA63);
        jPanelTodosDias.add(jPanelDIA64);
        jPanelTodosDias.add(jPanelDIA65);
        jPanelTodosDias.add(jPanelDIA66);
        jPanelTodosDias.add(jPanelDIA67);

        add(jPanelTodosDias, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        try{
            jPopupMenuEvento.setVisible(false);
            JTableRenderEventoParam loDia = jPanelTableRender1.getParam();
            if(moEventos.moList.buscar(
                    JListDatos.mclTIgual
                    , new int[]{moEventos.lPosiCALENDARIO, moEventos.lPosiCODIGO}
                    ,new String[]{
                        loDia.getCalendario(), loDia.getCodigo()
                    })){
                moControlador.editar(moEventos.moList.getIndex());
            }else{
                JOptionPane.showMessageDialog(this, "No existe una fila actual");
            }
        } catch (Exception ex) {
            JMsgBox.mensajeError(this, ex);
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed

        try{
            jPopupMenuEvento.setVisible(false);
            if (JOptionPane.showConfirmDialog(this,
                    "¿Estas seguro de borrar el registro actual?",
                    "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                JTableRenderEventoParam loDia = jPanelTableRender1.getParam();
                if(moEventos.moList.buscar(
                        JListDatos.mclTIgual
                        , new int[]{moEventos.lPosiCALENDARIO, moEventos.lPosiCODIGO}
                        ,new String[]{
                            loDia.getCalendario(), loDia.getCodigo()
                        })){
                    moControlador.borrar(moEventos.moList.getIndex());
                }else{
                    JOptionPane.showMessageDialog(this, "No existe una fila actual");
                }
            }
        } catch (Exception ex) {
            JMsgBox.mensajeError(this, ex);
        }

    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jPopupMenuEvento.setVisible(false);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ jBtnBorrar;
    private utilesGUIx.JButtonCZ jBtnEditar;
    private utilesGUIx.JButtonCZ jButtonCancelar;
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private utilesGUIx.JLabelCZ jLabelCZ2;
    private utilesGUIx.JLabelCZ jLabelCZ3;
    private utilesGUIx.JLabelCZ jLabelCZ4;
    private utilesGUIx.JLabelCZ jLabelCZ5;
    private utilesGUIx.JLabelCZ jLabelCZ6;
    private utilesGUIx.JLabelCZ jLabelCZ7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA11;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA12;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA13;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA14;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA15;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA16;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA17;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA21;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA22;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA23;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA24;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA25;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA26;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA27;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA31;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA32;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA33;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA34;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA35;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA36;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA37;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA41;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA42;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA43;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA44;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA45;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA46;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA47;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA51;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA52;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA53;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA54;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA55;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA56;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA57;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA61;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA62;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA63;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA64;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA65;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA66;
    private utilesGUIxAvisos.forms.util.JPanelDIA jPanelDIA67;
    private utilesGUIxAvisos.forms.util.JPanelTableRender jPanelTableRender1;
    private javax.swing.JPanel jPanelTodosDias;
    private javax.swing.JPanel jPanelver;
    private javax.swing.JPopupMenu jPopupMenuEvento;
    // End of variables declaration//GEN-END:variables

}
