/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelTableRender.java
 *
 * Created on 06-nov-2011, 9:39:49
 */
package utilesGUIxAvisos.forms.util;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;

/**
 *
 * @author eduardo
 */
public class JPanelTableRenderDIA extends javax.swing.JPanel {
    private Font moFuenteStandar = new Font("Dialog", Font.PLAIN, 12);
    private Font moFuenteTachado;
    
    /** Creates new form JPanelTableRender */
    public JPanelTableRenderDIA() {
        initComponents();
        
        Map  attributes = moFuenteStandar.getAttributes();
        attributes.put(TextAttribute.STRIKETHROUGH, TextAttribute.STRIKETHROUGH_ON);
        moFuenteTachado = new Font(attributes); 
    
    }
    void setValue(JTableRenderEventoParam poPAram, boolean pbIsSelected) {
        
        lblPrioridad.setBackground(poPAram.getPrioridad());
        lblTarea.setText(
                poPAram.getFechaDesde().msFormatear("HH:mm") 
                + " " +
                poPAram.getNombre());
        if(poPAram.isAviso()){
            lblTarea.setFont(moFuenteTachado);
        } else {
            lblTarea.setFont(moFuenteStandar); 
        }
        
        if(pbIsSelected){
            setBorder(
                    new javax.swing.border.LineBorder(
                        javax.swing.UIManager.getDefaults().getColor("Table.selectionBackground"), 4, true));

        }else{
            setBorder(null);
        }    
        validate();
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPrioridad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTarea = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(20, 50));
        setPreferredSize(new java.awt.Dimension(300, 55));
        setLayout(new java.awt.GridBagLayout());

        lblPrioridad.setText(" ");
        lblPrioridad.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(lblPrioridad, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTarea.setBackground(new java.awt.Color(51, 51, 51));
        lblTarea.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(lblTarea, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPrioridad;
    private javax.swing.JLabel lblTarea;
    // End of variables declaration//GEN-END:variables

}
