/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelOpcionesSMS.java
 *
 * Created on 27-oct-2011, 10:36:08
 */
package utilesGUIxAvisos.avisos.forms;

import utilesGUIx.Rectangulo;
import ListDatos.JFilaDatosDefecto;
import ListDatos.JSTabla;

import utilesGUI.tiposTextos.JTipoTextoEstandar;

import utilesGUIx.formsGenericos.edicion.JPanelGENERALBASE;
import utilesGUIxAvisos.avisos.JGUIxAvisosDatosGenerales;

/**
 *
 * @author eduardo
 */
public class JPanelOpcionesCorreo  extends JPanelGENERALBASE {
    private JGUIxAvisosDatosGenerales moDatos;
    /** Creates new form JPanelOpcionesGenerales */
    public JPanelOpcionesCorreo() {
        initComponents();
    }
    
    public void setDatos(JGUIxAvisosDatosGenerales poDatos){
        moDatos=poDatos;
    }

    public JSTabla getTabla() {
        return null;
    }

    public void rellenarPantalla() throws Exception {
        cmbSeguridad.borrarTodo();
        cmbSeguridad.addLinea("", String.valueOf(moDatos.mclSeguridadNada)+JFilaDatosDefecto.mcsSeparacion1);
        cmbSeguridad.addLinea("SSL/TLS", String.valueOf(moDatos.mclSeguridadSSL)+JFilaDatosDefecto.mcsSeparacion1);
        cmbSeguridad.addLinea("startTLS", String.valueOf(moDatos.mclSeguridadstarttls)+JFilaDatosDefecto.mcsSeparacion1);
        

    }

    public void habilitarSegunEdicion() throws Exception {
    }

    public void ponerTipoTextos() throws Exception {
        txtCORREO_CORREO.setTipo(JTipoTextoEstandar.mclTextCadena); 
        txtCORREO_CORREONOMBRE.setTipo(JTipoTextoEstandar.mclTextCadena); 
        txtCORREO_SMTP.setTipo(JTipoTextoEstandar.mclTextCadena); 
        txtCORREO_USUARIO.setTipo(JTipoTextoEstandar.mclTextCadena); 
        txtCORREO_PUERTO.setTipo(JTipoTextoEstandar.mclTextCadena); 

    }
    public void mostrarDatos() throws Exception {

        txtCORREO_CORREO.setText(moDatos.getCorreo()); 
        txtCORREO_CORREONOMBRE.setText(moDatos.getCorreoNombre()); 
        txtCORREO_SMTP.setText(moDatos.getCorreoSMTP()); 
        txtCORREO_PASSWORD.setText(moDatos.getCorreoSMTPPassword()); 
        txtCORREO_USUARIO.setText(moDatos.getCorreoSMTPUsuario()); 
        txtCORREO_PUERTO.setText(String.valueOf(moDatos.getCorreoSMTPPuerto())); 
        cmbSeguridad.setValueTabla(moDatos.getCorreoSMTPSeguridad()+JFilaDatosDefecto.mcsSeparacion1);
    }

    public boolean validarDatos() throws Exception{
        return true;
    }

    public void establecerDatos() throws Exception {

        moDatos.setCorreo(txtCORREO_CORREO.getText()); 
        moDatos.setCorreoNombre(txtCORREO_CORREONOMBRE.getText()); 
        moDatos.setCorreoSMTP(txtCORREO_SMTP.getText()); 
        moDatos.setCorreoSMTPPassword(txtCORREO_PASSWORD.getText()); 
        moDatos.setCorreoSMTPUsuario(txtCORREO_USUARIO.getText()); 

        try{
            moDatos.setCorreoSMTPSeguridad(Integer.valueOf(cmbSeguridad.getFilaActual().msCampo(0)).intValue());
        }catch(Throwable e){
            moDatos.setCorreoSMTPSeguridad(moDatos.mclSeguridadNada);
        }
        
        moDatos.setCorreoSMTPPuerto(Integer.valueOf(txtCORREO_PUERTO.getText()).intValue()); 
    }

    public void cancelar() throws Exception {
        moDatos.cancelar();
    }

    public void aceptar() throws Exception {
        moDatos.aceptar();
    }


    public Rectangulo getTanano() {
        return new Rectangulo(0,0, 89, 45);
    }

    public String getTitulo() {
        return "Correo";
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabelCZ6 = new utilesGUIx.JLabelCZ();
        txtCORREO_CORREO = new utilesGUIx.JTextFieldCZ();
        jLabelCZ7 = new utilesGUIx.JLabelCZ();
        txtCORREO_CORREONOMBRE = new utilesGUIx.JTextFieldCZ();
        jLabelCZ8 = new utilesGUIx.JLabelCZ();
        txtCORREO_SMTP = new utilesGUIx.JTextFieldCZ();
        jLabelCZ9 = new utilesGUIx.JLabelCZ();
        txtCORREO_USUARIO = new utilesGUIx.JTextFieldCZ();
        jLabelCZ10 = new utilesGUIx.JLabelCZ();
        txtCORREO_PASSWORD = new javax.swing.JPasswordField();
        jLabelCZ11 = new utilesGUIx.JLabelCZ();
        cmbSeguridad = new utilesGUIx.JComboBoxCZ();
        jLabelCZ12 = new utilesGUIx.JLabelCZ();
        txtCORREO_PUERTO = new utilesGUIx.JTextFieldCZ();

        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelCZ6.setText("Correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ6, gridBagConstraints);

        txtCORREO_CORREO.setMinimumSize(new java.awt.Dimension(100, 19));
        txtCORREO_CORREO.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(txtCORREO_CORREO, gridBagConstraints);

        jLabelCZ7.setText("Nombre correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ7, gridBagConstraints);

        txtCORREO_CORREONOMBRE.setMinimumSize(new java.awt.Dimension(100, 19));
        txtCORREO_CORREONOMBRE.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(txtCORREO_CORREONOMBRE, gridBagConstraints);

        jLabelCZ8.setText("Servidor SMTP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ8, gridBagConstraints);

        txtCORREO_SMTP.setMinimumSize(new java.awt.Dimension(100, 19));
        txtCORREO_SMTP.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(txtCORREO_SMTP, gridBagConstraints);

        jLabelCZ9.setText("SMTP usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ9, gridBagConstraints);

        txtCORREO_USUARIO.setMinimumSize(new java.awt.Dimension(100, 19));
        txtCORREO_USUARIO.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(txtCORREO_USUARIO, gridBagConstraints);

        jLabelCZ10.setText("SMTP password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(txtCORREO_PASSWORD, gridBagConstraints);

        jLabelCZ11.setText("Seguridad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(cmbSeguridad, gridBagConstraints);

        jLabelCZ12.setText("Puerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(jLabelCZ12, gridBagConstraints);

        txtCORREO_PUERTO.setMinimumSize(new java.awt.Dimension(100, 19));
        txtCORREO_PUERTO.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel2.add(txtCORREO_PUERTO, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JComboBoxCZ cmbSeguridad;
    private utilesGUIx.JLabelCZ jLabelCZ10;
    private utilesGUIx.JLabelCZ jLabelCZ11;
    private utilesGUIx.JLabelCZ jLabelCZ12;
    private utilesGUIx.JLabelCZ jLabelCZ6;
    private utilesGUIx.JLabelCZ jLabelCZ7;
    private utilesGUIx.JLabelCZ jLabelCZ8;
    private utilesGUIx.JLabelCZ jLabelCZ9;
    private javax.swing.JPanel jPanel2;
    private utilesGUIx.JTextFieldCZ txtCORREO_CORREO;
    private utilesGUIx.JTextFieldCZ txtCORREO_CORREONOMBRE;
    private javax.swing.JPasswordField txtCORREO_PASSWORD;
    private utilesGUIx.JTextFieldCZ txtCORREO_PUERTO;
    private utilesGUIx.JTextFieldCZ txtCORREO_SMTP;
    private utilesGUIx.JTextFieldCZ txtCORREO_USUARIO;
    // End of variables declaration//GEN-END:variables
}
