/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelOpcionesSMS.java
 *
 * Created on 27-oct-2011, 10:36:08
 */
package utilesGUIxAvisos.avisos.forms;

import ListDatos.JSTabla;
import java.awt.Rectangle;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import utiles.JDepuracion;
import utilesGUIx.Rectangulo;
import utilesGUIx.formsGenericos.edicion.JPanelGENERALBASE;
import utilesGUIx.msgbox.JMsgBox;
import utilesGUIxAvisos.avisos.JGUIxAvisosDatosGenerales;
import utilesGUIxAvisos.avisos.tablasControladoras.JT2CUENTASCORREO;

/**
 *
 * @author eduardo
 */
public class JPanelOpcionesAvisos  extends JPanelGENERALBASE {

    private JT2CUENTASCORREO moCuentasCorreo;
    private JGUIxAvisosDatosGenerales moDatos;
    
    /** Creates new form JPanelOpcionesGenerales */
    public JPanelOpcionesAvisos() {
        initComponents();
    }
    
    public void setDatos(JGUIxAvisosDatosGenerales poDatos){
        moDatos = poDatos;
        jPanelOpcionesSMS1.setDatos(poDatos);
    }

    @Override
    public JSTabla getTabla() {
        return null;
    }

    @Override
    public void rellenarPantalla() throws Exception {
        jPanelOpcionesSMS1.rellenarPantalla();

    }

    @Override
    public void habilitarSegunEdicion() throws Exception {
        jPanelOpcionesSMS1.habilitarSegunEdicion();
    }

    @Override
    public void ponerTipoTextos() throws Exception {
        jPanelOpcionesSMS1.ponerTipoTextos();
    }
    @Override
    public void mostrarDatos() throws Exception {
        jPanelOpcionesSMS1.mostrarDatos();
        moCuentasCorreo = new JT2CUENTASCORREO(moDatos.getListaCorreos());
        jPanelGenerico1.setControlador(moCuentasCorreo);
        txtPLANTILLA.setText(moDatos.getPathPlantilla());
    }

    @Override
    public boolean validarDatos() throws Exception{
        return true;
    }

    @Override
    public void establecerDatos() throws Exception {
        jPanelOpcionesSMS1.establecerDatos();
        moDatos.setPathPlantilla(txtPLANTILLA.getText()); 
    }

    @Override
    public void cancelar() throws Exception {
        jPanelOpcionesSMS1.cancelar();
    }

    @Override
    public void aceptar() throws Exception {

        moDatos.aceptar();
    }


    @Override
    public Rectangulo getTanano() {
        return new Rectangulo(0,0, 89, 45);
    }

    @Override
    public String getTitulo() {
        return "Avisos";
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelOpcionesCorreo1 = new javax.swing.JPanel();
        jPanelGenerico1 = new utilesGUIx.formsGenericos.JPanelGenerico();
        jLabelPlantilla = new utilesGUIx.JLabelCZ();
        txtPLANTILLA = new javax.swing.JTextField();
        jButtonSeleccionPlantilla = new javax.swing.JButton();
        jPanelOpcionesSMS1 = new utilesGUIxAvisos.avisos.forms.JPanelOpcionesSMS();

        setLayout(new java.awt.GridBagLayout());

        jPanelOpcionesCorreo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanelOpcionesCorreo1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelOpcionesCorreo1.add(jPanelGenerico1, gridBagConstraints);

        jLabelPlantilla.setText("Plantilla:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanelOpcionesCorreo1.add(jLabelPlantilla, gridBagConstraints);

        txtPLANTILLA.setEditable(false);
        txtPLANTILLA.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.9;
        jPanelOpcionesCorreo1.add(txtPLANTILLA, gridBagConstraints);

        jButtonSeleccionPlantilla.setText("Seleccionar");
        jButtonSeleccionPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionPlantillaActionPerformed(evt);
            }
        });
        jPanelOpcionesCorreo1.add(jButtonSeleccionPlantilla, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanelOpcionesCorreo1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanelOpcionesSMS1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionPlantillaActionPerformed
        try{
            JFileChooser loFileM = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Plantilla GTC", new String[]{"gtc"});
            loFileM.setFileFilter(filter);
            loFileM.setAcceptAllFileFilterUsed(false);
            if (loFileM.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                if (!loFileM.getSelectedFile().getPath().endsWith(".gtc")) {
                    throw new Exception("La plantilla debe tener la extensión .gtc");
                }
                txtPLANTILLA.setText(loFileM.getSelectedFile().getPath());
            } else {
                txtPLANTILLA.setText("");
            }
        }catch(Exception e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            JMsgBox.mensajeError(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSeleccionPlantillaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeleccionPlantilla;
    private utilesGUIx.JLabelCZ jLabelPlantilla;
    private utilesGUIx.formsGenericos.JPanelGenerico jPanelGenerico1;
    public javax.swing.JPanel jPanelOpcionesCorreo1;
    public utilesGUIxAvisos.avisos.forms.JPanelOpcionesSMS jPanelOpcionesSMS1;
    private javax.swing.JTextField txtPLANTILLA;
    // End of variables declaration//GEN-END:variables
}
