/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JMostrarPantallaFormsAbiertos.java
 *
 * Created on 02-sep-2011, 23:35:30
 */
package utilesGUIx.formsGenericos;

import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import utiles.IListaElementos;

/**
 *
 * @author eduardo
 */
public class JMostrarPantallaFormsAbiertos extends javax.swing.JFrame {
    private JMostrarPantallaSwing moMostrar;

    /** Creates new form JMostrarPantallaFormsAbiertos */
    public JMostrarPantallaFormsAbiertos() {
        initComponents();
        if(utilesGUIx.JGUIxConfigGlobal.getInstancia().getMostrarPantalla().getImagenIcono()!=null){
            this.setIconImage(((ImageIcon) utilesGUIx.JGUIxConfigGlobal.getInstancia().getMostrarPantalla().getImagenIcono()).getImage());
        }          
        int ancho = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth());
        int alto = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight());
        alto -= 40;
        Rectangle loRect =  new Rectangle(0,0,ancho,alto);
        setBounds(loRect);
        setState(MAXIMIZED_BOTH);
        
    }
    public void setDatos(final JMostrarPantallaSwing poMostrar) throws Exception{
        moMostrar = poMostrar;
        IListaElementos loElem = moMostrar.getElementos();
        if(((int)loElem.size() / 2) == loElem.size() / 2.0){
            getContentPane().setLayout(new java.awt.GridLayout(0,loElem.size()/2));
        }else{
            getContentPane().setLayout(new java.awt.GridLayout(0,loElem.size()/2 +1));
        }
        if(loElem.size() == 1 ){
            getContentPane().setLayout(new java.awt.GridLayout(0,1));
        }else if(loElem.size() == 2 ){
            getContentPane().setLayout(new java.awt.GridLayout(0,2));
        }
        for(int i = 0 ; i < loElem.size(); i++){
            final JMostrarPantallaFormulario loForm = (JMostrarPantallaFormulario) loElem.get(i);
            JMostrarPantallaForm loB = new JMostrarPantallaForm(JMostrarPantalla.getImage(loForm.getForm()));
            loB.setText(loForm.getParam().getTitulo());
            loB.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    loForm.mostrarFrente();
                    JMostrarPantallaFormsAbiertos.this.dispose();
                }
            });
            this.getContentPane().add(loB);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
