/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package impresionXML.impresion.xml.diseno.componentes;

import utilesGUIx.Rectangulo;
import ListDatos.IFilaDatos;
import ListDatos.JListDatos;
import ListDatos.JUtilTabla;
import impresionXML.impresion.xml.JxmlCuadrado;
import impresionXML.impresion.xml.JxmlFuente;
import impresionXML.impresion.xml.JxmlInforme;
import impresionXML.impresion.xml.diseno.campos.JTCAMPOS;
import java.awt.Color;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.geom.Point2D;
import javax.swing.JColorChooser;
import utilesGUI.tiposTextos.JTipoTextoEstandar;
import utilesGUIx.JFontChooser;

import utilesGUIx.formsGenericos.CallBack;
import utilesGUIx.formsGenericos.IPanelControlador;
import utilesGUIx.formsGenericos.busqueda.IConsulta;
import utilesGUIx.formsGenericos.busqueda.JBusqueda;
import utilesGUIx.formsGenericos.edicion.JPanelEdicionAbstract;
import utilesGUIx.msgbox.JMsgBox;

/**
 *
 * @author eduardo
 */
public class JPanelFuentePROPER extends JPanelEdicionAbstract implements ActionListener, FocusListener {
    private JxmlFuente moFuente;
    private JxmlInforme moInforme;
    private boolean mbMostrarDatos=false;

    /**
     * Creates new form JPanelFuenteVIEW
     */
    public JPanelFuentePROPER() {
        initComponents();
        txtNombre.addActionListener(this);
        txtNombre.addFocusListener(this);
    }
    
    public void setDatos(JxmlFuente poFuente, JxmlInforme poInforme){
        moFuente=poFuente;
        moInforme=poInforme;
    }


    public void rellenarPantalla() throws Exception {
        mbMostrarDatos=true;
        try{
        }finally{
            mbMostrarDatos=false;
        }
        
    }

    public void habilitarSegunEdicion() throws Exception {
    }

    public void ponerTipoTextos() throws Exception {
    }

    public void mostrarDatos() throws Exception {
        mbMostrarDatos=true;
        try{
            txtNombre.setValueTabla(moFuente.getNombre());
            lblFuente.setText(moFuente.getFuente() + " " + String.valueOf(moFuente.getSize()) + " " 
                    + (moFuente.isBold() ? " Negrita" : "" )  
                    + (moFuente.isCursiva()? " Cursiva" : "" )  
                    + (moFuente.isUnderline()? " Subrayado" : "" )  
                    + (moFuente.isTachado()? " Tachado" : "" )  
                    );
            lblFuente.setFont(moFuente.getFont());
        }finally{
            mbMostrarDatos=false;
        }
    }

    public void establecerDatos() throws Exception {
        moFuente.setFuente(lblFuente.getFont().getFamily());
        moFuente.setSize(lblFuente.getFont().getSize());
        moFuente.setBold(lblFuente.getFont().isBold());
        moFuente.setCursiva(lblFuente.getFont().isItalic());

        moFuente.setNombre(txtNombre.getText());
    }
    public void aceptar() throws Exception {
        moInforme.add(moFuente);
    }

    public void cancelar() throws Exception {
    }


    public Rectangulo getTanano() {
        return new Rectangulo(800, 600);
    }

    public String getTitulo() {
        return "Fuente";
    }
    public void actionPerformed(ActionEvent e) {
        try {
            if(!mbMostrarDatos){
                establecerDatos();
            }
        } catch (Exception ex) {
            JMsgBox.mensajeErrorYLog(this, ex);
        }
    }
    public void focusGained(FocusEvent e) {
    }

    public void focusLost(FocusEvent e) {
        actionPerformed(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        txtNombre = new utilesGUIx.JTextFieldCZ();
        btnBuscarNombre = new utilesGUIx.JButtonCZ();
        lblFuente = new utilesGUIx.JLabelCZ();
        btnSelecFuente = new utilesGUIx.JButtonCZ();
        lblColor = new utilesGUIx.JLabelCZ();
        btnEliminar = new utilesGUIx.JButtonCZ();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fuente");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabel1, gridBagConstraints);

        jLabelCZ1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(jLabelCZ1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(txtNombre, gridBagConstraints);

        btnBuscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impresionXML/impresion/xml/diseno/img/Zoom16.gif"))); // NOI18N
        btnBuscarNombre.setToolTipText("Buscar nombre");
        btnBuscarNombre.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBuscarNombre.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBuscarNombre.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(btnBuscarNombre, gridBagConstraints);

        lblFuente.setText("Fuente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(lblFuente, gridBagConstraints);

        btnSelecFuente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impresionXML/impresion/xml/diseno/img/Zoom16.gif"))); // NOI18N
        btnSelecFuente.setToolTipText("Seleccionar fuente");
        btnSelecFuente.setMaximumSize(new java.awt.Dimension(25, 25));
        btnSelecFuente.setMinimumSize(new java.awt.Dimension(25, 25));
        btnSelecFuente.setPreferredSize(new java.awt.Dimension(25, 25));
        btnSelecFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecFuenteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(btnSelecFuente, gridBagConstraints);

        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setText("Color");
        lblColor.setOpaque(true);
        lblColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColorMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(lblColor, gridBagConstraints);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impresionXML/impresion/xml/diseno/img/Delete16.gif"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(btnEliminar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColorMouseClicked

        //        final JColorChooser colorChooser = new JColorChooser();         
        Color loColor = JColorChooser.showDialog(this, "", lblColor.getBackground());         
        if (loColor != null) {             
            lblColor.setBackground(loColor);         
        }     
        actionPerformed(null);
        
    }//GEN-LAST:event_lblColorMouseClicked

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        try {
            
            JBusqueda loBus = new JBusqueda(new IConsulta() {
                JTCAMPOS loCampos;

                public void refrescar(boolean pbPasarACache, boolean pbLimpiarCache) throws Exception {
                    loCampos = moInforme.getDiseno().getTablaCamposPredefinidos();
                    loCampos.getList().getFiltro().addCondicionAND(JListDatos.mclTIgual, JTCAMPOS.lPosiTIPO, JxmlFuente.mcsNombreXml);
                    loCampos.getList().filtrar();
                    loCampos.moList = JUtilTabla.clonarFilasListDatos(loCampos.getList(), false);
                }

                public JListDatos getList() {
                    return loCampos.moList;
                }

                public void addFilaPorClave(IFilaDatos poFila) throws Exception {
                }

                public boolean getPasarCache() {
                    return false;
                }
            }, "Campos");
            
            loBus.getParametros().setCallBack(new CallBack<IPanelControlador>() {

                public void callBack(IPanelControlador poControlador) {
                    try {
                        poControlador.getConsulta().getList().setIndex(poControlador.getIndex());
                        txtNombre.setText(poControlador.getConsulta().getList().getFields(JTCAMPOS.lPosiNOMBRE).getString());
                        establecerDatos();
                    } catch (Exception ex) {
                        JMsgBox.mensajeErrorYLog(JPanelFuentePROPER.this, ex);
                    }
                }
            });
            
            loBus.mostrarBusq();
            
        } catch (Exception ex) {
            JMsgBox.mensajeErrorYLog(this, ex);
        }

    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            moInforme.getBanda(0).remove(moFuente);
            moFuente = new JxmlFuente();
            mostrarDatos();
        } catch (Exception ex) {
            JMsgBox.mensajeErrorYLog(this, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSelecFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecFuenteActionPerformed
        try {

            JFontChooser loFontCh = new JFontChooser();
            loFontCh.setSelectedFont(lblFuente.getFont());
            if(loFontCh.showDialog(this)==loFontCh.OK_OPTION){
                lblFuente.setFont(loFontCh.getSelectedFont());
                establecerDatos();
                mostrarDatos();
            }
        } catch (Exception ex) {
            JMsgBox.mensajeErrorYLog(this, ex);
        }        
    }//GEN-LAST:event_btnSelecFuenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnBuscarNombre;
    private utilesGUIx.JButtonCZ btnEliminar;
    private utilesGUIx.JButtonCZ btnSelecFuente;
    private javax.swing.JLabel jLabel1;
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private utilesGUIx.JLabelCZ lblColor;
    private utilesGUIx.JLabelCZ lblFuente;
    private utilesGUIx.JTextFieldCZ txtNombre;
    // End of variables declaration//GEN-END:variables



}
