/*
 * JFormPropiedades.java
 *
 * Created on 19 de febrero de 2007, 11:16
 */

package utilesGUIx.configForm.antig;

import utilesGUIx.configForm.antig.JPanelPropiedades;
import java.awt.BorderLayout;

public class JFormPropiedades extends javax.swing.JFrame {
    public JPanelPropiedades jPanelPropiedades1;
    /** Creates new form JFormPropiedades */
    public JFormPropiedades() {
        initComponents();
        jPanelPropiedades1 = new JPanelPropiedades();
        getContentPane().add(jPanelPropiedades1, BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-418)/2, (screenSize.height-335)/2, 418, 335);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
