/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package impresionXML.impresion.xml.diseno;

import utilesGUIx.Rectangulo;
import java.awt.Rectangle;
import utilesGUI.tiposTextos.JTipoTextoEstandar;

import utilesGUIx.formsGenericos.edicion.JPanelEdicionAbstract;

/**
 *
 * @author eduardo
 */
public class JPanelParametros extends JPanelEdicionAbstract {
    private JT2Parametros moObjeto;

    /**
     * Creates new form JPanelParametros
     */
    public JPanelParametros() {
        initComponents();
    }

    public void setDatos(JT2Parametros poParam) {
        moObjeto = poParam;
    }

    public void rellenarPantalla() throws Exception {
        lblX.setVisible(moObjeto.mbPresentarX);
        lblY.setVisible(moObjeto.mbPresentarY);
        txtX.setVisible(moObjeto.mbPresentarX);
        txtY.setVisible(moObjeto.mbPresentarY);
        
    }
    public void habilitarSegunEdicion() throws Exception {
    }
    public void ponerTipoTextos() throws Exception {
        txtX.setTipo(JTipoTextoEstandar.mclTextNumeroDoble);
        txtY.setTipo(JTipoTextoEstandar.mclTextNumeroDoble);
    }
    public void mostrarDatos() throws Exception {
        jLabel1.setText(moObjeto.mstitulo);
        txtX.setValueTabla(String.valueOf(moObjeto.x));
        txtY.setValueTabla(String.valueOf(moObjeto.y));
    }
    public void establecerDatos() throws Exception {
        moObjeto.x=Double.valueOf(txtX.getText()).doubleValue();
        moObjeto.y=Double.valueOf(txtY.getText()).doubleValue();
    }
    public void aceptar() throws Exception {
        moObjeto.mbCancelado=false;
    }
    public void cancelar() throws Exception {
        moObjeto.mbCancelado=true;
    }

    public Rectangulo getTanano() {
        return new Rectangulo(400, 400);
    }

    public String getTitulo() {
        return "Parámetros";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        lblX = new utilesGUIx.JLabelCZ();
        txtX = new utilesGUIx.JTextFieldCZ();
        lblY = new utilesGUIx.JLabelCZ();
        txtY = new utilesGUIx.JTextFieldCZ();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabel1, gridBagConstraints);

        lblX.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(lblX, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(txtX, gridBagConstraints);

        lblY.setText("Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(lblY, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(txtY, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private utilesGUIx.JLabelCZ lblX;
    private utilesGUIx.JLabelCZ lblY;
    private utilesGUIx.JTextFieldCZ txtX;
    private utilesGUIx.JTextFieldCZ txtY;
    // End of variables declaration//GEN-END:variables

}
