/*
 * JFormBorradoAWT.java
 *
 * Created on 26 de noviembre de 2004, 9:56
 */

package utilesGUI.borradoRelaciones;

import ListDatos.*;
import utilesGUI.tabla.*;

import utiles.*;
import utilesBD.relaciones.*;
/**Formulario que muestra los registros relacionados a borrar*/
public class JFormBorradoAWT extends java.awt.Dialog {
    private JRelacionTablaRegistros moTabla;
    private JComunicacion moComu;
    private JTablaMotorSimple moModeloDatos;
        
    /**
     * Creates new form JFormBorrado
     * @param parent padre
     * @param modal si es modal
     */
    public JFormBorradoAWT(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * Establecemos los datos a ver
     * @param poTabla Lista de registros relacionados
     * @param poComu para devolver si ha aceptado o no
     */
    public void setTabla(JRelacionTablaRegistros poTabla, JComunicacion poComu){
        moTabla = poTabla;
        moComu = poComu;
        
        setTitle("Mensaje antes de borrar");
        jLabel1.setText("Se borraran los siguientes datos de la tabla " + moTabla.msTabla + " ¿Desea continuar?");
        moModeloDatos = new JTablaMotorSimple(moTabla.moFields, moTabla.moFilas);
        jTabla1.setTabla(moModeloDatos);

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new java.awt.Label();
        jTabla1 = new utilesGUI.tabla.JTabla();
        panel1 = new java.awt.Panel();
        btnSi = new utilesGUI.ButtonCZ();
        btnNo = new utilesGUI.ButtonCZ();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("label1");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        add(jTabla1, java.awt.BorderLayout.CENTER);

        btnSi.setLabel("S\u00ed");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        panel1.add(btnSi);

        btnNo.setLabel("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        panel1.add(btnNo);

        add(panel1, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-411)/2, (screenSize.height-300)/2, 411, 300);
    }//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        moComu.moObjecto = new Boolean(false);
        dispose();        
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        moComu.moObjecto = new Boolean(true);
        dispose();
    }//GEN-LAST:event_btnSiActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUI.ButtonCZ btnNo;
    private utilesGUI.ButtonCZ btnSi;
    private java.awt.Label jLabel1;
    private utilesGUI.tabla.JTabla jTabla1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
    
}
