/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package utilesGUIx.aplicacion.avisosGUI;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import utilesGUIx.aplicacion.avisos.IAvisoListener;
import utilesGUIx.aplicacion.avisos.JAviso;
import utilesGUIx.aplicacion.avisos.JAvisosConj;

/**
 *
 * @author eduardo
 */
public class JPanelAvisosConj extends javax.swing.JPanel implements IAvisoListener {
    private JAvisosConj moAvisos;
    private JTableModelAvisos moModeloDatosEventos;        

    /**
     * Creates new form JPanelGeneralAvisos2
     */
    public JPanelAvisosConj() {
        initComponents();
        jTableDatos.setRowHeight(45);        
    }
    
    public void setDatos(JAvisosConj poAvisos){
        moAvisos=poAvisos;
        
        moModeloDatosEventos = new JTableModelAvisos(poAvisos);
        jTableDatos.setModel(moModeloDatosEventos);
        jTableDatos.setDefaultRenderer(JAviso.class, new JTableRenderAvisos(poAvisos));
        jTableDatos.getColumnModel().getColumn(0).setCellRenderer(new JTableRenderAvisos(poAvisos));
        jTableDatos.getColumnModel().getColumn(0).setCellEditor(new JTableEditAvisos(poAvisos));
        jTableDatos.setRowHeight(45);
        
        moAvisos.removeListener(this);
        moAvisos.addListener(this);
        
    }
    public void avisoPerformed(tiposAvisoListener plTipo, JAviso poAviso, JAvisosConj poConj) {
        try{
            jTableDatos.getCellEditor().cancelCellEditing();
        }catch(Exception e){}
        jTableDatos.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnLimpiarTodo = new utilesGUIx.JButtonCZ();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnLimpiarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/emptytrash.png"))); // NOI18N
        btnLimpiarTodo.setToolTipText("Limpiar todo");
        btnLimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTodoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(btnLimpiarTodo, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDatos);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTodoActionPerformed
        moAvisos.clear();
    }//GEN-LAST:event_btnLimpiarTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnLimpiarTodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDatos;
    // End of variables declaration//GEN-END:variables


}
