/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelTableRender.java
 *
 * Created on 06-nov-2011, 9:39:49
 */
package utilesGUIx.aplicacion.avisosGUI;

import javax.swing.ImageIcon;
import utilesGUIx.aplicacion.avisos.JAviso;
import utilesGUIx.aplicacion.avisos.JAvisosConj;
import utilesGUIx.formsGenericos.IMostrarPantalla;

/**
 *
 * @author eduardo
 */
public class JPanelTableRenderAvisos extends javax.swing.JPanel {
    private static final ImageIcon imageINFORMATION = new ImageIcon(JPanelTableRenderAvisos.class.getResource("/utilesGUIx/images/dialog-information.png"));
    private static final ImageIcon imageWARNING = new ImageIcon(JPanelTableRenderAvisos.class.getResource("/utilesGUIx/images/dialog-warning.png"));
    private static final ImageIcon imageERROR = new ImageIcon(JPanelTableRenderAvisos.class.getResource("/utilesGUIx/images/dialog-error.png"));

    private JAviso moAviso;
    private JAvisosConj moAvisosConj;

    /** Creates new form JPanelTableRender */
    public JPanelTableRenderAvisos() {
        initComponents();
    }
    void setValue(JAviso poAviso, boolean pbIsSelected, JAvisosConj poAvisosConj) {
        moAvisosConj=poAvisosConj;
        moAviso=poAviso;
        switch(moAviso.getTipoMensaje()){
            case IMostrarPantalla.mclMensajeAdvertencia:
                lblTipoMensaje.setIcon(imageWARNING);
                break;
            case IMostrarPantalla.mclMensajeError:
                lblTipoMensaje.setIcon(imageERROR);
                break;
            case IMostrarPantalla.mclMensajeInformacion:
                lblTipoMensaje.setIcon(imageINFORMATION);
                break;
        }
        
        lblMensaje.setText(poAviso.getMensaje());
        lblMensaje.setToolTipText(poAviso.getMensaje());
        jButton1.setEnabled(moAviso.getAccion()!=null);
        
        if(pbIsSelected){
            setBorder(
                    new javax.swing.border.LineBorder(
                        javax.swing.UIManager.getDefaults().getColor("Table.selectionBackground"), 4, true));

        }else{
            setBorder(null);
        }    
        
        validate();
    }
    
    public JAviso getValue(){
        return moAviso;
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTipoMensaje = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(20, 30));
        setPreferredSize(new java.awt.Dimension(20, 30));
        setLayout(new java.awt.GridBagLayout());

        lblTipoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/dialog-information.png"))); // NOI18N
        lblTipoMensaje.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(lblTipoMensaje, gridBagConstraints);

        lblMensaje.setBackground(new java.awt.Color(51, 51, 51));
        lblMensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(lblMensaje, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/FastForward16.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jButton1, gridBagConstraints);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/emptytrash.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        moAviso.getAccion().actionPerformed(null);
        jButton2ActionPerformed(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        moAvisosConj.remove(moAviso);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTipoMensaje;
    // End of variables declaration//GEN-END:variables

}
