/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JGuiSelectCamposRapidoAsistente.java
 *
 * Created on 17-may-2010, 12:04:21
 */

package paquetesGeneradorInf.gui.camposRapido;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import paquetesGeneradorInf.gui.JGuiConsultaDatos;
import utilesGUIx.JGUIxConfigGlobal;

public class JGuiSelectCamposRapidoAsistente extends javax.swing.JPanel {
    private static final long serialVersionUID = 1;

    public static final int mclSelectCampos = 1;
    public static final int mclResultado = 2;
    public static final int mclEjecutar = 2;
    public static final int mclFin = 3;

    private JGuiConsultaDatos moConsulta;
    private int mlPaso;

    /** Creates new form JGuiSelectCamposRapidoAsistente */
    public JGuiSelectCamposRapidoAsistente() {
        initComponents();
    }
    
    public void setConsulta(JGuiConsultaDatos poDatos) throws Exception {
        moConsulta=poDatos;
        jGuiResultados1.setConsulta(moConsulta);
        jGuiSelectCamposRapido1.setConsulta(moConsulta);
        setPaso(mclSelectCampos);
    }
    private void guardar() {
        jGuiSelectCamposRapido1.guardar();
    }

    public void setPaso(int plPaso) throws Exception{
        switch(plPaso){
            case mclSelectCampos:
                btnAnterior.setEnabled(false);
                btnSiguiente.setEnabled(true);
                btnFinalizar.setEnabled(true);
                ((CardLayout)jPanelCentral.getLayout()).show(jPanelCentral, String.valueOf(plPaso));
                break;
            case mclResultado:
                guardar();
                jGuiResultados1.setConsulta(moConsulta);
                jGuiResultados1.refrescar();
                btnAnterior.setEnabled(true);
                btnSiguiente.setEnabled(false);
                btnFinalizar.setEnabled(true);
                ((CardLayout)jPanelCentral.getLayout()).show(jPanelCentral, String.valueOf(plPaso));
                break;
            default:
                try{
                    JGUIxConfigGlobal.getInstancia().getMostrarPantalla().cerrarForm(this);
                }catch(Exception e){
                    SwingUtilities.getWindowAncestor(this).dispose();
                }                


        }
        mlPaso = plPaso;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotones = new javax.swing.JPanel();
        btnAnterior = new utilesGUIx.JButtonCZ();
        btnSiguiente = new utilesGUIx.JButtonCZ();
        btnFinalizar = new utilesGUIx.JButtonCZ();
        jPanelCentral = new javax.swing.JPanel();
        jGuiSelectCamposRapido1 = new paquetesGeneradorInf.gui.camposRapido.JGuiSelectCamposRapido();
        jGuiResultados1 = new paquetesGeneradorInf.gui.resultados.JGuiResultados();

        setLayout(new java.awt.BorderLayout());

        jPanelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquetesGeneradorInf/images/Back16.gif"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanelBotones.add(btnAnterior);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquetesGeneradorInf/images/Forward16.gif"))); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanelBotones.add(btnSiguiente);

        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquetesGeneradorInf/images/accept.gif"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanelBotones.add(btnFinalizar);

        add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        jPanelCentral.setLayout(new java.awt.CardLayout());
        jPanelCentral.add(jGuiSelectCamposRapido1, "1");
        jPanelCentral.add(jGuiResultados1, "2");

        add(jPanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try{
            setPaso(mlPaso-1);
        }catch(Throwable e){
            utilesGUIx.msgbox.JMsgBox.mensajeErrorYLog(this, e, getClass().getName());
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try{
            setPaso(mlPaso+1);
        }catch(Throwable e){
            utilesGUIx.msgbox.JMsgBox.mensajeErrorYLog(this, e, getClass().getName());
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        try{
            setPaso(mclFin);
        }catch(Throwable e){
            utilesGUIx.msgbox.JMsgBox.mensajeErrorYLog(this, e, getClass().getName());
        }

    }//GEN-LAST:event_btnFinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnAnterior;
    private utilesGUIx.JButtonCZ btnFinalizar;
    private utilesGUIx.JButtonCZ btnSiguiente;
    private paquetesGeneradorInf.gui.resultados.JGuiResultados jGuiResultados1;
    private paquetesGeneradorInf.gui.camposRapido.JGuiSelectCamposRapido jGuiSelectCamposRapido1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCentral;
    // End of variables declaration//GEN-END:variables


}
