/*
 * JPanelPapelera.java
 *
 * Created on 19 de agosto de 2008, 11:09
 */

package utilesDoc.forms;


import ListDatos.IFilaDatos;
import ListDatos.IResultado;
import java.awt.Cursor;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import utiles.JDepuracion;
import utilesDoc.tablasExtend.JDocImagenBasica;
import utilesDoc.tablasExtend.JTEEDOCUMENTOS;
import utilesDoc.tablasExtend.JTEEDOCUMTIPOS;
import utilesGUIx.ActionEventCZ;
import utilesGUIx.formsGenericos.JT2GENERALBASEModelo;
import utilesGUIx.formsGenericos.busqueda.IConsulta;
import utilesGUIx.imgTrata.JIMGTrata;
import utilesGUIx.seleccionFicheros.JFileChooserFiltroPorExtension;


public class JPanelDoc extends javax.swing.JPanel {
    private JTEEDOCUMENTOS moDoc = null;
    private ImageIcon moIconNoPDF = null;
    private String msDirActual = "";
    private ImageIcon moIcono;
    private JDocImagenBasica moDocimg;
    private String msGrupo;
    private String msGrupoIdent;
    private final ImageIcon moIconError;

    /** Creates new form JPanelPapelera */
    public JPanelDoc() {
        initComponents();
         moIconNoPDF = new ImageIcon(getClass().getResource("/utilesGUIx/images/NoPdf.png"));
         moIconError = new ImageIcon(getClass().getResource("/utilesGUIx/images/dialog-error.png"));
         
   }
    
    public void setDatos(JTEEDOCUMENTOS poDoc, String psGrupo, String psGrupoIdent) throws Exception {
        moDoc = poDoc;
        msGrupo=psGrupo;
        msGrupoIdent=psGrupoIdent;
        ponerIcono();
        
    }
    
    private void ponerIcono() throws Exception{
        if(!moDoc.moveFirst()){
            imgPDF.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            moDocimg=null;
            moIcono = moIconNoPDF;
        } else {
            moDocimg = new JDocImagenBasica(moDoc.moList.moServidor);
            try {
                moDocimg.setDatos(moDoc.moList.moFila());
                moIcono=moDocimg.getImagen();
            } catch (Throwable ex) {
                moDocimg=null;
                moIcono = moIconError;
                JDepuracion.anadirTexto(getClass().getName(), ex);
            }
            imgPDF.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        redimensionar();
    }
    private void redimensionar(){
        if(moIcono!=null) {
            if(moIcono == moIconNoPDF || moIcono == moIconError){
                imgPDF.setIcon(moIcono);
            }else{
                if(moIcono.getIconWidth() > imgPDF.getWidth() 
                        || moIcono.getIconHeight() > imgPDF.getHeight() ){
                    ImageIcon loIcon =  new ImageIcon(
                        JIMGTrata.getIMGTrata().getImagenEscalada(
                            moIcono.getImage()
                            , moIcono.getIconWidth(), moIcono.getIconHeight()
                            , imgPDF.getWidth()>0 ? imgPDF.getWidth() : 80
                            , imgPDF.getHeight()>0 ? imgPDF.getHeight() : 80
                        ));

                    imgPDF.setIcon(loIcon);
                }else{
                    imgPDF.setIcon(moIcono);
                }
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        imgPDF = new javax.swing.JLabel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("Establecer imagen");
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        imgPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPDFMouseClicked(evt);
            }
        });
        imgPDF.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imgPDFComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                imgPDFComponentShown(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(imgPDF, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

        btnMas.setBackground(new java.awt.Color(255, 255, 255));
        btnMas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/mas.png"))); // NOI18N
        btnMas.setToolTipText("Añadir imagen/PDF");
        btnMas.setFocusable(false);
        btnMas.setIconTextGap(1);
        btnMas.setPreferredSize(new java.awt.Dimension(25, 25));
        btnMas.setRequestFocusEnabled(false);
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(btnMas, gridBagConstraints);

        btnMenos.setBackground(new java.awt.Color(255, 255, 255));
        btnMenos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/menos.png"))); // NOI18N
        btnMenos.setToolTipText("Borrar");
        btnMenos.setFocusable(false);
        btnMenos.setIconTextGap(1);
        btnMenos.setPreferredSize(new java.awt.Dimension(25, 25));
        btnMenos.setRequestFocusEnabled(false);
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(btnMenos, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void imgPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPDFMouseClicked

        try{
            if(moDocimg!=null){
                moDocimg.ver();
            }
        }catch(Throwable e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }
    }//GEN-LAST:event_imgPDFMouseClicked


    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        try {
            //Selecciono el archivo PDF
            JFileChooser loOpen = new JFileChooser();
            JFileChooserFiltroPorExtension loFiltro = new JFileChooserFiltroPorExtension(
                    "Imagenes"
                    , JTEEDOCUMTIPOS.getExtensionesImagenes(moDoc.moList.moServidor)
            );
            loOpen.setFileSelectionMode(JFileChooser.FILES_ONLY);
            loOpen.setFileFilter(loFiltro);
            if(!msDirActual.equals("")) {
                loOpen.setCurrentDirectory(new File(msDirActual));
            }
            if(loOpen.showOpenDialog(new javax.swing.JLabel())==JFileChooser.APPROVE_OPTION ){
                try {
                    
                    File loFile = loOpen.getSelectedFile();
                    if(!moDoc.moveFirst()){
                        moDoc.moList.addNew();
                    }
                    moDoc.getGRUPO().setValue(msGrupo);
                    moDoc.getGRUPOIDENT().setValue(msGrupoIdent);

                    moDoc.setDatosDefecto(loFile);
                    moDoc.validarCampos();
                    IResultado loResult=moDoc.guardar(new JT2GENERALBASEModelo() {
                        @Override
                        public IConsulta getConsulta() {return null;}
                        @Override
                        public void anadir() throws Exception {}
                        @Override
                        public void borrar(int plIndex) throws Exception {}
                        @Override
                        public void editar(int plIndex) throws Exception {}
                        @Override
                        public void mostrarFormPrinci() throws Exception {}
                        @Override
                        public void actionPerformed(ActionEventCZ e, int[] plIndex) throws Exception {}
                        @Override
                        public void datosactualizados(IFilaDatos poFila) throws Exception {
                            ponerIcono();
                        }
                        
                    });
                    if(!loResult.getBien()){
                        throw new Exception(loResult.getMensaje());
                    }
                    msDirActual = loOpen.getSelectedFile().getParent();
                    ponerIcono();
                } catch (Exception ex) {
                    JDepuracion.anadirTexto(getClass().getName(), ex);
                }
            } else {
                imgPDF.setIcon(moIconNoPDF);
            }
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }
        
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        
        try{
            moDoc.borrar();
            ponerIcono();
        }catch(Throwable e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }        
    }//GEN-LAST:event_btnMenosActionPerformed

    private void imgPDFComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imgPDFComponentResized
        try{
        redimensionar();
        }catch(Throwable e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }        
        
    }//GEN-LAST:event_imgPDFComponentResized

    private void imgPDFComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imgPDFComponentShown
        try{
        redimensionar();
        }catch(Throwable e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }        
        
    }//GEN-LAST:event_imgPDFComponentShown
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JLabel imgPDF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
