/*
 * ColorSeleccion.java
 *
 * Created on 10 de enero de 2006, 9:47
 */

package utilesGUI;

import java.awt.Color;
        
public class ColorSeleccion extends java.awt.Panel implements java.awt.event.ActionListener {
    
    /** Creates new form ColorSeleccion */
    public ColorSeleccion() {
        initComponents();
        btnSelec.addActionListener(this);
    }
    
    public Color getColor(){
        return canvas1.getBackground();
    }
    public void setColor(Color c){
        canvas1.setBackground(c);
    }

    public void actionPerformed(java.awt.event.ActionEvent e) {
//        setColor(javax.swing.JColorChooser.showDialog(this, "Seleccionar color", getColor()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        canvas1 = new java.awt.Canvas();
        btnSelec = new java.awt.Button();

        setLayout(new java.awt.GridBagLayout());

        canvas1.setBackground(java.awt.Color.white);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(canvas1, gridBagConstraints);

        btnSelec.setLabel("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(btnSelec, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSelec;
    private java.awt.Canvas canvas1;
    // End of variables declaration//GEN-END:variables
    
}
