/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelSeleccionarFoto.java
 *
 * Created on 25-ene-2009, 10:38:11
 */

package utilesGUIx.imgTrata.seleccionar;

import ListDatos.JFilaDatosDefecto;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import utiles.JDepuracion;
import utilesGUIx.JGUIxConfigGlobal;
import utilesGUIx.imgTrata.JPanelVistaPrevia;
import utilesGUIx.imgTrata.lista.JImagenBasica;
import utilesGUIx.seleccionFicheros.JFileChooserFiltroPorExtension;

/**
 *
 * @author eduardo
 */
public class JPanelSeleccionarFoto extends javax.swing.JPanel {
    private JAccionesSeleccionarFotoPanel moAccion;
    private JPanelVistaPrevia moVista;
    private Thread moThread;
    private JVerImagen moVerImagen;
    /** Creates new form JPanelSeleccionarFoto
     * @param poAccion */
    public JPanelSeleccionarFoto(JAccionesSeleccionarFotoPanel poAccion) {
        try {
            initComponents();
            JGUIxConfigGlobal.getInstancia().setTextoTodosComponent(this);
            moVista = new JPanelVistaPrevia();
            add(moVista, BorderLayout.CENTER);
            moAccion = poAccion;
            chkLimpiarDirectorio.setSelected(moAccion.isLimpiarDirectorio());
            if(moAccion.getArchivo()==null){
//                utilesGUIx.msgbox.JMsgBox.mensajeInformacion(this, "No existe ninguna imagen en el directorio");
//                btnSeleccionarActionPerformed(null);
//                chkDefecto.setSelected(true);
            }else{
                visualizar(moAccion.getArchivo());
            }
        } catch (Throwable ex) {
            ex.printStackTrace();
        }
    }


    public void visualizar(final File poImagen) {
        if(moThread!=null){
            moVerImagen.setCancelar(true);
        }
        moVista.setImagen(new javax.swing.ImageIcon(
                getClass().getResource("/utilesGUIx/images/ani20.gif")
        ).getImage());
        moVerImagen = new JVerImagen(poImagen);
        moThread = new Thread(moVerImagen);
        moThread.start();

    }
    class JVerImagen implements Runnable {

        private final File moImagen;
        private boolean mbCancelar=false;
        public JVerImagen(final File poImagen){
            moImagen=poImagen;
        }
        public void run() {
            JImagenBasica loImgBasica = new JImagenBasica(0, 0);
            if(moImagen!=null){
                try {
                    loImgBasica.setDatos(new JFilaDatosDefecto(new String[]{moImagen.getAbsolutePath()}));
                    if(!mbCancelar){
                        moVista.setImagen(loImgBasica.getImagen().getImage());
                    }
                } catch (Throwable ex) {
                    ImageIcon loIcon = new ImageIcon(getClass().getResource("/utilesGUIx/images/crossed_circle.png"));
                    moVista.setImagen(loIcon.getImage());
                            
                    JDepuracion.anadirTexto(getClass().getName(), ex);
                }
            }else{
                moVista.setImagen((Image)null);
            }
        }
        public void setCancelar(boolean pbCancelar){
            mbCancelar=pbCancelar;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        chkDefecto = new utilesGUIx.JCheckBoxCZ();
        chkLimpiarDirectorio = new utilesGUIx.JCheckBoxCZ();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/accept.gif"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new java.awt.GridBagConstraints());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/cancel.gif"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new java.awt.GridBagConstraints());

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIx/images/Find16.gif"))); // NOI18N
        btnSeleccionar.setText("Buscar...");
        btnSeleccionar.setToolTipText("Buscar otra imagen");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new java.awt.GridBagConstraints());

        chkDefecto.setText("Ruta defecto");
        chkDefecto.setToolTipText("Selecciona como ruta por defecto la ruta que tiene la imagen actual");
        jPanel1.add(chkDefecto, new java.awt.GridBagConstraints());

        chkLimpiarDirectorio.setText("Limpiar directorio");
        chkLimpiarDirectorio.setToolTipText("Selecciona como ruta por defecto la ruta que tiene la imagen actual");
        jPanel1.add(chkLimpiarDirectorio, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try {
            if(moAccion.getArchivo()==null){
                throw new Exception("Imagen vacía");
            }
            //selecionamos la ruta defecto
            if(chkDefecto.isSelected()){
                moAccion.setRutaDefecto(moAccion.getArchivo().getParent());
            }
            //limpiar directorio
            moAccion.setLimpiarDirectorio(chkLimpiarDirectorio.isSelected());

            moAccion.setCancelado(false);
            setVisible(false);
            JGUIxConfigGlobal.getInstancia().getMostrarPantalla().cerrarForm(this);
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        try {
            moAccion.setCancelado(true);
            setVisible(false);
            JGUIxConfigGlobal.getInstancia().getMostrarPantalla().cerrarForm(this);
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

        try {
            String[] las = new String[moAccion.getExtensiones().size()];
            String lsTitulo = "";
            int i = 0;
            for(String ls : moAccion.getExtensiones()){
                lsTitulo+=ls + ",";
                las[i++]=ls;
            }
            JFileChooser loSelec = new JFileChooser(moAccion.getRutaDefecto());
            loSelec.setFileFilter(
                    new JFileChooserFiltroPorExtension(lsTitulo,las));
            if(loSelec.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
                visualizar(loSelec.getSelectedFile());
                moAccion.setArchivo(loSelec.getSelectedFile());
            }
        } catch (Throwable ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }


}//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private utilesGUIx.JCheckBoxCZ chkDefecto;
    private utilesGUIx.JCheckBoxCZ chkLimpiarDirectorio;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
