/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JGuiResultados.java
 *
 * Created on 28-may-2009, 11:42:12
 */

package paquetesGeneradorInf.gui.resultados;

import paquetesGeneradorInf.gui.JGuiConsultaDatos;
import utilesGUIx.JTableModel;

public class JGuiResultados extends javax.swing.JPanel {
    private JGuiConsultaDatos moConsulta;
    private JGuiResultadosControlador moControlador;


    /** Creates new form JGuiResultados */
    public JGuiResultados() {
        initComponents();
    }

    public void setConsulta(JGuiConsultaDatos poConsulta) {
        moConsulta = poConsulta;
    }

    public void refrescar() throws Exception {
        moControlador = new JGuiResultadosControlador(moConsulta);
        moControlador.inicializar();
        jPanelGenerico21.setControlador(moControlador);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGenerico21 = new utilesGUIx.formsGenericos.JPanelGenerico2();

        setLayout(new java.awt.BorderLayout());
        add(jPanelGenerico21, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.formsGenericos.JPanelGenerico2 jPanelGenerico21;
    // End of variables declaration//GEN-END:variables

}
