/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFormMensajeImp.java
 *
 * Created on 25-mar-2010, 11:27:18
 */

package impresionJasper.msgbox;

import ListDatos.JListDatos;
import impresionJasper.JMotorInformes;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import utiles.JDepuracion;
import utilesGUIx.JButtonCZ;


public class JFormMensajeImp extends utilesGUIx.msgbox.JFormMensaje {
    private utilesGUIx.JButtonCZ btnImprimir;

    /** Creates new form JFormMensajeImp */
    public JFormMensajeImp(Frame poPadre, boolean pbModal, String psTexto, String psTitulo) {
        super(poPadre, pbModal, psTexto);
//        initComponents();
        setTituloInfo(psTitulo);
        btnImprimir = new JButtonCZ();
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impresionJasper/images/Print16.gif"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }

        });
        getPanelBotonera().add(btnImprimir);
    }
    private void btnImprimirActionPerformed(ActionEvent evt) {
        try{
            JImprimirUtils.imprimirTexto(getTitulo(), getMensajeHTML());
        }catch(Throwable e){
            utilesGUIx.msgbox.JMsgBox.mensajeErrorYLog(this, e, getClass().getName() );
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-430)/2, 640, 430);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        JFormMensajeImp loForm = new JFormMensajeImp(null, false, "", "titulo");
        loForm.addError("prueba 1");
        loForm.addError("prueba 2");
        loForm.addError("prueba 3");
        loForm.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
