/*
 * JFormBorrado.java
 *
 * Created on 22 de noviembre de 2004, 10:03
 */

package utilesGUIx.borradoRelaciones;

import javax.swing.*;

import ListDatos.*;
import utilesGUI.tabla.*;

import utiles.*;
import utilesGUIx.*;
import utilesBD.relaciones.*;

/**Formulario que muestra los registros relacionados a borrar*/
public class JFormBorrado extends javax.swing.JDialog implements java.awt.event.ActionListener {
    private JRelacionTablaRegistros moTabla;
    private JComunicacion moComu;
    private utilesGUIx.JTableModelSimple moModeloDatos;
    
    /**
     * Creates new form JFormBorrado
     * @param parent padre
     * @param modal si es modal
     */
    public JFormBorrado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * Establecemos los datos a ver
     * @param poTabla datos
     * @param poComu para devolver el resultado
     */
    public void setTabla(JRelacionTablaRegistros poTabla, JComunicacion poComu){
        moTabla = poTabla;
        moComu = poComu;
        
        setTitle("Mensaje antes de borrar");
        jLabel1.setText("Se borraran los siguientes datos de la tabla " + moTabla.msTabla + " ¿Desea continuar?");
        moModeloDatos = new utilesGUIx.JTableModelSimple(moTabla.moFields, moTabla.moFilas);
        jTable1.setModel(moModeloDatos);

        //solo se puede seleccionar una fila
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new utilesGUIx.JTableCZ();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        btnSi.setLabel("S\u00ed");
        btnSi.addActionListener(this);

        jPanel1.add(btnSi);

        btnNo.setLabel("No");
        btnNo.addActionListener(this);

        jPanel1.add(btnNo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBackground(new java.awt.Color(237, 234, 229));
        jScrollPane1.setBorder(null);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("ppp");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnSi) {
            JFormBorrado.this.btnSiActionPerformed(evt);
        }
        else if (evt.getSource() == btnNo) {
            JFormBorrado.this.btnNoActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        moComu.moObjecto = Boolean.TRUE;
        dispose();
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        moComu.moObjecto = Boolean.FALSE;
        dispose();
    }//GEN-LAST:event_btnNoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private utilesGUIx.JTableCZ jTable1;
    // End of variables declaration//GEN-END:variables
    
}

