/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPropiedadesCompApl.java
 *
 * Created on 01-sep-2011, 18:09:00
 */
package utilesGUIx.plugin.toolBar;

import utilesGUIx.Rectangulo;
import java.awt.Rectangle;
import utiles.JConversiones;
import utilesGUI.tiposTextos.JTipoTextoEstandar;

import utilesGUIx.formsGenericos.edicion.JPanelEdicionAbstract;

/**
 *
 * @author eduardo
 */
public class JPanelPropiedadesCompApl extends JPanelEdicionAbstract {
    private IComponenteAplicacion moComp;

    /** Creates new form JPanelPropiedadesCompApl */
    public JPanelPropiedadesCompApl() {
        initComponents();
    }
    public void setDatos(IComponenteAplicacion poComp){
        moComp=poComp;
    } 
    public void rellenarPantalla() throws Exception {
        if(!(moComp instanceof JComponenteAplicacionGrupo )){
            txtnumeroColumnas.setVisible(false);
            lblnumerocolumnas.setVisible(false);
        }
    }

    public void habilitarSegunEdicion() throws Exception {
    }

    public void ponerTipoTextos() throws Exception {
        txtnumeroColumnas.setTipo(JTipoTextoEstandar.mclTextNumeroEntero);
    }

    public void mostrarDatos() throws Exception {
        if(moComp instanceof JComponenteAplicacionGrupo ){
            txtnumeroColumnas.setText(String.valueOf(((JComponenteAplicacionGrupo)moComp).getColumnasDeBotones()));
        }
        txtTitulo.setText(moComp.getCaption());
    }

    public void establecerDatos() throws Exception {
        if(moComp instanceof JComponenteAplicacionGrupo ){
            ((JComponenteAplicacionGrupo)moComp).setColumnasDeBotones((int)JConversiones.cdbl(txtnumeroColumnas.getText()));
        }
        moComp.setCaption(txtTitulo.getText());
        
    }
    public void aceptar() throws Exception {
    }

    public void cancelar() throws Exception {
    }


    public Rectangulo getTanano() {
        return new Rectangulo(300, 300);
    }

    public String getTitulo() {
        return "Propiedades " + moComp.getCaption();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        txtTitulo = new utilesGUIx.JTextFieldCZ();
        lblnumerocolumnas = new utilesGUIx.JLabelCZ();
        txtnumeroColumnas = new utilesGUIx.JTextFieldCZ();

        setLayout(new java.awt.GridBagLayout());

        jLabelCZ1.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(jLabelCZ1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(txtTitulo, gridBagConstraints);

        lblnumerocolumnas.setText("Número botones por fila");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(lblnumerocolumnas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(txtnumeroColumnas, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private utilesGUIx.JLabelCZ lblnumerocolumnas;
    private utilesGUIx.JTextFieldCZ txtTitulo;
    private utilesGUIx.JTextFieldCZ txtnumeroColumnas;
    // End of variables declaration//GEN-END:variables


}
