/*
 * JDepuracionForm.java
 *
 * Created on 26 de mayo de 2006, 18:22
 */

package utilesGUI.depuracion;

public class JDepuracionForm extends java.awt.Frame {
    
    /** Creates new form JDepuracionForm */
    public JDepuracionForm() {
        super();
        initComponents();
        setSize(400,300);
              
    }
    
    public void addTexto(String psTexto){
        textAreaCZ1.append('\n'+psTexto);
        if(textAreaCZ1.getText().length()>20000){
            textAreaCZ1.setText(textAreaCZ1.getText().substring(20000));
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        button1 = new java.awt.Button();
        textAreaCZ1 = new java.awt.TextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        button1.setForeground(new java.awt.Color(0, 0, 0));
        button1.setLabel("Aceptar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel1.add(button1);

        add(panel1, java.awt.BorderLayout.SOUTH);
        add(textAreaCZ1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        dispose();
    }//GEN-LAST:event_button1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Panel panel1;
    private java.awt.TextArea textAreaCZ1;
    // End of variables declaration//GEN-END:variables
    
}
