/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelEdicionBlanco.java
 *
 * Created on 10-dic-2010, 17:56:46
 */

package utilesGUIx.formsGenericos.edicion;

import java.awt.Component;

/**
 *
 * @author eduardo
 */
public class JPanelEdicionBlanco extends javax.swing.JPanel {

    /** Creates new form JPanelEdicionBlanco */
    public JPanelEdicionBlanco() {
        initComponents();
    }
    /**
     * Establecemos el panel de los datos
     * @param poPanel Cotnrolador
     * @param poPanelMismo componente a insertar en form.
     * @throws Exception error
     */
    public void setPanel(IFormEdicion poPanel, Component poPanelMismo) throws Exception {
        add(poPanelMismo, java.awt.BorderLayout.CENTER);

        poPanel.rellenarPantalla();
        poPanel.ponerTipoTextos();
        poPanel.habilitarSegunEdicion();
        JPanelEdicion.mostrarDatosBD(this);
        poPanel.mostrarDatos();
        jLabelAvisos1.setAvisos(poPanel.getParametros().getAvisos());
        jLabelAvisos1.setVisible(poPanel.getParametros().getAvisos().size()>0);
        if(poPanel.getParametros() !=null){
            poPanel.getParametros().getBotones().add(jLabelAvisos1);
        }
        setBounds(poPanel.getTanano().x, poPanel.getTanano().y, poPanel.getTanano().width, poPanel.getTanano().height);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAvisos1 = new utilesGUIx.aplicacion.avisosGUI.JLabelAvisos();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelAvisos1.setText(" ");
        jPanel1.add(jLabelAvisos1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.aplicacion.avisosGUI.JLabelAvisos jLabelAvisos1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
