/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utilesGUIx.formsGenericos.edicion;

import ListDatos.JListDatos;
import ListDatos.JSTabla;
import javax.swing.table.TableColumn;
import utilesGUIx.JTableCZ;
import utilesGUIx.JTableCZSelecCeldas;

/**
 *
 * @author eduardo
 */
public class JPanelEdicionTable extends javax.swing.JPanel {

    private JTableModelEdicionTable moModel;
    private JPanelEdicionTableParametros moParam;
    private final JTableCZSelecCeldas moSelectCeldas;
    /**
     * Creates new form JPanelEdicionTable
     */
    public JPanelEdicionTable() {
        initComponents();
        moSelectCeldas = new JTableCZSelecCeldas(jTableCZ1);
    }
    
    public JTableCZ getTable(){
        return jTableCZ1;
    }
    public void setList(JSTabla poList, JPanelEdicionTableParametros poParam){
        moModel = new JTableModelEdicionTable(poList);
        jTableCZ1.setModel(moModel);
        moParam = poParam;
        if(moParam!=null){
            if(moParam.getLongitudCampos()!=null){
                for(int i = 0 ; i < moParam.getLongitudCampos().length; i++){
                    ponerColumnaWidth(i, moParam.getLongitudCampos()[i]);
                }
            }
        }
    }
    private void ponerColumnaWidth(int i, int plWidth){
        TableColumn loColumn;
        loColumn = jTableCZ1.getColumnModel().getColumn(i);
        if(plWidth==0){
            loColumn.setMinWidth(0);
            loColumn.setPreferredWidth(0);
            loColumn.setWidth(0);
            loColumn.setMaxWidth(0);
        }else{
            loColumn.setPreferredWidth(plWidth);
            loColumn.setWidth(plWidth);
        }
	
    }
    
    public JTableModelEdicionTable getModel(){
        return moModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCZ1 = new utilesGUIx.JTableCZ();

        setLayout(new java.awt.BorderLayout());

        jTableCZ1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCZ1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTableCZ1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private utilesGUIx.JTableCZ jTableCZ1;
    // End of variables declaration//GEN-END:variables
}
