/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JGuiSelectTablasMostrar.java
 *
 * Created on 19-jun-2009, 10:38:48
 */

package paquetesGeneradorInf.gui;

import ListDatos.estructuraBD.JTableDef;
import ListDatos.estructuraBD.JTableDefs;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import utiles.JDepuracion;

public class JGuiSelectTablasMostrar extends javax.swing.JPanel {
    private JGuiSelectTablas moSelectTablas;
    private JGuiConsultaDatos moDatos;

    /** Creates new form JGuiSelectTablasMostrar */
    public JGuiSelectTablasMostrar() {
        initComponents();
    }

    public void setDatos(JGuiSelectTablas poSelectTablas, JGuiConsultaDatos poDatos) throws Exception{
        moSelectTablas=poSelectTablas;
        moDatos=poDatos;
        mostrar();
    }
    private void mostrar() throws Exception{
        jListCZ1.borrarTodo();
        JTableDefs loTablas =  moSelectTablas.getConsulta().getDatos().getServer().getTableDefs();
        for(int i = 0 ; i < loTablas.getListaTablas().size(); i++){
            JTableDef loTabla = loTablas.get(i);
            if(!moDatos.isTablaAExcluir(loTabla.getNombre())){
                if(loTabla.getTipo()!= JTableDef.mclTipoSystem){
                    jListCZ1.addLinea(
                            getNombreTabla(loTabla.getNombre()),
                            loTabla.getNombre()
                            );
                }
            }
        }
    }
    private String getNombreTabla(String psTabla) {
        String lsResult = "";
        //nombre tabla
        if (moSelectTablas.getConsulta().getDatos().isUsarNombresFisicos()) {
            lsResult = psTabla;
        } else {
            if(moSelectTablas.getConsulta().getDatos().getTextosForms().getString(psTabla).equals(psTabla)){
                lsResult = psTabla;
            }else{
                lsResult = psTabla +
                        "("+
                        moSelectTablas.getConsulta().getDatos().getTextosForms().getString(psTabla) +
                        ")";
            }
        }

        return lsResult;
    }

    private void addTabla(String psTabla) throws Exception{
        moSelectTablas.addTabla(psTabla);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCZ2 = new utilesGUIx.JButtonCZ();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCZ1 = new utilesGUIx.JListCZ();
        jPanel1 = new javax.swing.JPanel();
        btnADD = new utilesGUIx.JButtonCZ();
        btnSalir = new utilesGUIx.JButtonCZ();

        jButtonCZ2.setText("jButtonCZ2");

        setLayout(new java.awt.BorderLayout());

        jListCZ1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListCZ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCZ1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListCZ1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnADD.setText("Agregar");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        jPanel1.add(btnADD);

        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        try{
            addTabla(jListCZ1.getFilaActual().msCampo(0));
        }catch(Exception e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try{
            moSelectTablas.getConsulta().getDatos().getMostrarPantalla().cerrarForm(this);
        }catch(Exception e){
            SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jListCZ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCZ1MouseClicked
        try{
            if(evt.getClickCount()>1){
                addTabla(jListCZ1.getFilaActual().msCampo(0));
            }
        }catch(Exception e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }

    }//GEN-LAST:event_jListCZ1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnADD;
    private utilesGUIx.JButtonCZ btnSalir;
    private utilesGUIx.JButtonCZ jButtonCZ2;
    private utilesGUIx.JListCZ jListCZ1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
