/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JGuiConsulta.java
 *
 * Created on 27-may-2009, 12:23:00
 */

package paquetesGeneradorInf.gui;

import ListDatos.JSelect;
import ListDatos.JSelectCampo;
import utiles.JDepuracion;

public class JGuiConsulta extends javax.swing.JPanel {
    private JGuiConsultaDatos moDatos = null;

    /** Creates new form JGuiConsulta */
    public JGuiConsulta() throws Exception {
        initComponents();
        jGuiSelectCampos1.setConsulta(this);
        jGuiSelectTablas1.setConsulta(this);
    }

    public void setDatos(JGuiConsultaDatos poDatos) throws Exception{
        moDatos = poDatos;
        jGuiResultados1.setConsulta(moDatos);
        jGuiSelectCampos1.mostrar();
        jGuiSelectTablas1.cambioTablas();
        jPanel1.setVisible(poDatos.getCallBack()!=null);
        jPanel2.setVisible(poDatos.getCallBack()!=null);
        if(poDatos.getCallBack()==null){
            jTabbedPane1.remove(jScrollObs);
        }
        txtNombre.setValueTabla(poDatos.getNombre());
        txtObs.setValueTabla(poDatos.getObservaciones());
        poDatos.setCancelado(true);//por defecto no se guarda
    }

    public JGuiConsultaDatos getDatos(){
        return moDatos;
    }

    public JSelect getSelect(){
        return moDatos.getSelect();
    }

    public void cambioTablasDETABLAS() throws Exception{
        jGuiSelectCampos1.cambioTablas();
    }
    public void setAgrupado(boolean pbAgrupado) throws Exception{
        jGuiSelectCampos1.setAgrupado(pbAgrupado);
    }
    public void addCampo(JSelectCampo poCampo) throws Exception{
        jGuiSelectCampos1.addCampo(poCampo);
    }

    public void guardar() throws Exception{
        jGuiSelectCampos1.guardar();
        jGuiSelectTablas1.guardar();
        moDatos.setNombre(txtNombre.getText());
        moDatos.setObservaciones(txtObs.getText());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        txtNombre = new utilesGUIx.JTextFieldCZ();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGuiSelectTablas1 = new paquetesGeneradorInf.gui.JGuiSelectTablas();
        jGuiSelectCampos1 = new paquetesGeneradorInf.gui.JGuiSelectCampos();
        jGuiResultados1 = new paquetesGeneradorInf.gui.resultados.JGuiResultados();
        jGuiSQL1 = new paquetesGeneradorInf.gui.JGuiSQL();
        jScrollObs = new javax.swing.JScrollPane();
        txtObs = new utilesGUIx.JTextAreaCZ();
        jPanel2 = new javax.swing.JPanel();
        jButtonAceptar = new utilesGUIx.JButtonCZ();
        jButtonCancelar = new utilesGUIx.JButtonCZ();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelCZ1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel1.add(jLabelCZ1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel1.add(txtNombre, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setViewportView(jGuiSelectTablas1);

        jSplitPane1.setTopComponent(jScrollPane1);

        jGuiSelectCampos1.setMinimumSize(new java.awt.Dimension(100, 100));
        jSplitPane1.setRightComponent(jGuiSelectCampos1);

        jTabbedPane1.addTab("Diseño", jSplitPane1);
        jTabbedPane1.addTab("Ejecutar", jGuiResultados1);
        jTabbedPane1.addTab("SQL", jGuiSQL1);

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollObs.setViewportView(txtObs);

        jTabbedPane1.addTab("Observaciones", jScrollObs);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquetesGeneradorInf/images/accept.gif"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAceptar);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquetesGeneradorInf/images/cancel.gif"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        try {
            if(moDatos!=null){
                if(jTabbedPane1.getSelectedComponent() == jSplitPane1 ){
                    guardar();
                    jGuiSelectCampos1.mostrar();
                }else if(jTabbedPane1.getSelectedComponent() == jGuiResultados1){
                    guardar();
                    jGuiResultados1.refrescar();
                }else if(jTabbedPane1.getSelectedComponent() == jGuiSQL1){
                    guardar();
                    jGuiSQL1.setSelect(moDatos.getSelect());
                }else{

                }
            }
            updateUI();
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try {
            guardar();
            moDatos.setCancelado(false);
            moDatos.getCallBack().callBack(moDatos);
            moDatos.getMostrarPantalla().cerrarForm(this);
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        try {
        moDatos.setCancelado(true);
        moDatos.getCallBack().callBack(moDatos);
        moDatos.getMostrarPantalla().cerrarForm(this);
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex);
        }

    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ jButtonAceptar;
    private utilesGUIx.JButtonCZ jButtonCancelar;
    private paquetesGeneradorInf.gui.resultados.JGuiResultados jGuiResultados1;
    private paquetesGeneradorInf.gui.JGuiSQL jGuiSQL1;
    private paquetesGeneradorInf.gui.JGuiSelectCampos jGuiSelectCampos1;
    private paquetesGeneradorInf.gui.JGuiSelectTablas jGuiSelectTablas1;
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollObs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private utilesGUIx.JTextFieldCZ txtNombre;
    private utilesGUIx.JTextAreaCZ txtObs;
    // End of variables declaration//GEN-END:variables

}
