
/*
 * JInfGeneralJasperPAGE.java
 *
 * Created on 24-jul-2009, 21:19:43
 */

package impresionJasper;

import ar.com.fdvs.dj.domain.constants.Page;
import java.awt.Font;


public class JInfGeneralJasperSeleccionPAGE extends javax.swing.JDialog {
    private JInfGeneralJasper moGenerador;

    /** Creates new form JInfGeneralJasperPAGE */
    public JInfGeneralJasperSeleccionPAGE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setDatos(JInfGeneralJasper poGenerador){
        moGenerador=poGenerador;
        Page loPage = moGenerador.getPageAutomatico();
        if(loPage.getHeight() == Page.Page_A4_Portrait().getHeight() &&
           loPage.getWidth() == Page.Page_A4_Portrait().getWidth() ){
            optA4V.setSelected(true);
        }
        if(loPage.getHeight() == Page.Page_A4_Landscape().getHeight() &&
           loPage.getWidth() == Page.Page_A4_Landscape().getWidth() ){
            optA4H.setSelected(true);
        }
        if(loPage.getHeight() == JInfGeneralJasper.getPageA3().getHeight() &&
           loPage.getWidth() == JInfGeneralJasper.getPageA3().getWidth() ){
            optA3H.setSelected(true);
        }
        txtFD.setText(new Integer(moGenerador.getFuenteDetalle().getSize()).toString());
        txtFE.setText(new Integer(moGenerador.getFuenteEncabezado().getSize()).toString());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        optA4V = new javax.swing.JRadioButton();
        optA4H = new javax.swing.JRadioButton();
        optA3H = new javax.swing.JRadioButton();
        lblFD = new utilesGUIx.JLabelCZ();
        txtFD = new utilesGUIx.JTextFieldCZ();
        lblFE = new utilesGUIx.JLabelCZ();
        txtFE = new utilesGUIx.JTextFieldCZ();
        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new utilesGUIx.JButtonCZ();
        btnCancelar = new utilesGUIx.JButtonCZ();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(optA4V);
        optA4V.setText("A4 vertical");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(optA4V, gridBagConstraints);

        buttonGroup1.add(optA4H);
        optA4H.setText("A4 horizontal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(optA4H, gridBagConstraints);

        buttonGroup1.add(optA3H);
        optA3H.setText("A3 horizontal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(optA3H, gridBagConstraints);

        lblFD.setText("Tamaño Fuente detalle:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(lblFD, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(txtFD, gridBagConstraints);

        lblFE.setText("Tamaño Fuente encabezado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(lblFE, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(txtFE, gridBagConstraints);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impresionJasper/images/accept.gif"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impresionJasper/images/cancel.gif"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-282)/2, (screenSize.height-180)/2, 282, 180);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Page loPage = moGenerador.getPageAutomatico();
        if(optA3H.isSelected()){
            loPage.setHeight(JInfGeneralJasper.getPageA3().getHeight());
            loPage.setWidth(JInfGeneralJasper.getPageA3().getWidth());
        }
        if(optA4H.isSelected()){
            loPage.setHeight(Page.Page_A4_Landscape().getHeight());
            loPage.setWidth(Page.Page_A4_Landscape().getWidth());
        }
        if(optA4V.isSelected()){
            loPage.setHeight(Page.Page_A4_Portrait().getHeight());
            loPage.setWidth(Page.Page_A4_Portrait().getWidth());
        }
        moGenerador.setPageManual(loPage);
        Font loFuente = new Font(ar.com.fdvs.dj.domain.constants.Font._FONT_ARIAL, Font.PLAIN, new Integer(txtFD.getText()).intValue());
        moGenerador.setFuenteDetalle(loFuente);
        loFuente = new Font(ar.com.fdvs.dj.domain.constants.Font._FONT_ARIAL, Font.BOLD, new Integer(txtFE.getText()).intValue());
        moGenerador.setFuenteEncabezado(loFuente);

        dispose();

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        moGenerador.setPageManual(null);
        dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnAceptar;
    private utilesGUIx.JButtonCZ btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private utilesGUIx.JLabelCZ lblFD;
    private utilesGUIx.JLabelCZ lblFE;
    private javax.swing.JRadioButton optA3H;
    private javax.swing.JRadioButton optA4H;
    private javax.swing.JRadioButton optA4V;
    private utilesGUIx.JTextFieldCZ txtFD;
    private utilesGUIx.JTextFieldCZ txtFE;
    // End of variables declaration//GEN-END:variables

}
