/*
* JFormLogin.java
*
* Creado el 2/10/2008
*/

package utilesSincronizacion.forms;
import utilesSincronizacion.JDatosGeneralesP;
import ListDatos.*;
import java.awt.event.ActionListener;
import utilesSincronizacion.*;
import utiles.JDepuracion;
import utiles.IListaElementos;
import utiles.xml.dom.Element;
import utiles.config.JDatosGeneralesXML;

public class JFormLogin extends javax.swing.JDialog implements ActionListener {

    private static final String mcsUltUsuario = "UltUsuario";
    private static final String mcsUltTipoConexion = "UltTipoConexion";
    /** Creates new form JFormLogin */
    public JFormLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        recargarCombo();
    }
    
    private void recargarCombo(){
        jComboBoxCZ1.borrarTodo();
        jComboBoxCZ1.addLinea("Directo", "1");
        Element loServidores = JDatosGeneralesP.getDatosGenerales().getDatosGeneralesXML().getElemento(JDatosGeneralesXML.mcsCONEXIONSERVIDOR);
        if(loServidores!=null){
            IListaElementos loElem =  loServidores.getChildren();
            for(int i = 0 ; i < loElem.size(); i++){
                Element loAux = (Element)loElem.get(i);
                jComboBoxCZ1.addLinea(
                        loAux.getName(), 
                        loAux.getValue());

            }
        }
        jComboBoxCZ1.setSelectedIndex(0);
        jTextLogin.setText(getUltUsuario());

        jComboBoxCZ1.setSelectedIndex(getUltTipoConexion());

    }
        
    private String getUltUsuario(){
        return JDatosGeneralesP.getDatosGenerales().getDatosGeneralesXML().getPropiedad(mcsUltUsuario);
    }
    private int getUltTipoConexion(){
        try{
            return Integer.valueOf(JDatosGeneralesP.getDatosGenerales().getDatosGeneralesXML().getPropiedad(mcsUltTipoConexion)).intValue();
        }catch(Exception e){
            return 0;
        }
    }
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextLogin = new utilesGUIx.JTextFieldCZ();
        jLabel2 = new javax.swing.JLabel();
        jTextPassWord = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCZ1 = new utilesGUIx.JComboBoxCZ();
        jBtnConexionesBD = new utilesGUIx.JButtonCZ();
        jPanelBotones = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jTextLogin, gridBagConstraints);

        jLabel2.setText("PassWord");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jTextPassWord, gridBagConstraints);

        jLabel5.setText("Servidor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jComboBoxCZ1, gridBagConstraints);

        jBtnConexionesBD.setText("...");
        jBtnConexionesBD.addActionListener(this);
        jPanel2.add(jBtnConexionesBD, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelBotones.setBackground(new java.awt.Color(175, 181, 186));
        jPanelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonAceptar.setText("Login  ");
        jButtonAceptar.addActionListener(this);
        jPanelBotones.add(jButtonAceptar);

        jLabel4.setText("        ");
        jPanelBotones.add(jLabel4);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(this);
        jPanelBotones.add(jButtonCancelar);

        jPanel3.add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(807, 162));
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jBtnConexionesBD) {
            JFormLogin.this.jBtnConexionesBDActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonAceptar) {
            JFormLogin.this.jButtonAceptarActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonCancelar) {
            JFormLogin.this.jButtonCancelarActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try{
            if(jComboBoxCZ1.getFilaActual().msCampo(0).compareTo("1")==0){
                JDatosGeneralesP.getDatosGenerales().setServidor(JServerServidorDatos.mclTipoBD,"");
            }else{
                if(jComboBoxCZ1.getFilaActual().msCampo(0).compareTo(JDatosGeneralesP.getDatosGenerales().getDireccionRemoto())==0){
                    JDatosGeneralesP.getDatosGenerales().setServidor(JServerServidorDatos.mclTipoInternetComprimido,jComboBoxCZ1.getFilaActual().msCampo(0));
                }else{
                    JDatosGeneralesP.getDatosGenerales().setServidor(JServerServidorDatos.mclTipoInternet,jComboBoxCZ1.getFilaActual().msCampo(0));
                }
            }
            JDatosGeneralesP.getDatosGenerales().getDatosGeneralesXML().setPropiedad(mcsUltTipoConexion, String.valueOf(jComboBoxCZ1.getSelectedIndex()));
            JDatosGeneralesP.getDatosGenerales().getDatosGeneralesXML().setPropiedad(mcsUltUsuario, jTextLogin.getText());
            try {
                JDatosGeneralesP.getDatosGenerales().getDatosGeneralesXML().guardarFichero();
            } catch (Exception ex) {
                JDepuracion.anadirTexto(getClass().getName(), ex);
            }

            dispose();
        }catch(Throwable e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JDatosGeneralesP.getDatosGenerales().moServer = null;
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jBtnConexionesBDActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        try {
        JDatosGeneralesP.getDatosGenerales().mostrarPropiedadesConexionBD();
            recargarCombo();
        } catch(Exception e) {
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
    }                                                  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ jBtnConexionesBD;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private utilesGUIx.JComboBoxCZ jComboBoxCZ1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBotones;
    private utilesGUIx.JTextFieldCZ jTextLogin;
    private javax.swing.JPasswordField jTextPassWord;
    // End of variables declaration//GEN-END:variables
    
}
