/*
 * JFormConflictos.java
 *
 * Created on 6 de octubre de 2008, 11:47
 */

package utilesSincronizacion.forms;

import utilesSincronizacion.sincronizacion.*;
import java.awt.Frame;
import javax.swing.table.TableColumn;
import utiles.JDepuracion;
import utilesGUIx.JTableModel;
import utilesGUIx.formsGenericos.JMostrarPantalla;
import utilesGUIx.formsGenericos.JPanelGenerico;
import utilesSincronizacion.sincronizacion.conflictos.IFormConflictos;
import utilesSincronizacion.sincronizacion.conflictos.JListaElementosConflictos;
import utilesSincronizacion.sincronizacion.consultas.JCConflictos;

public class JFormConflictos extends javax.swing.JDialog implements java.awt.event.ActionListener, IFormConflictos {

    public static boolean mbCancelados = false;
    private JListaElementosConflictos moConflictos;
    private JCConflictos moConsultaConflictos;
    private JTableModel moModel;

    private JSincronizar moSincronizacion;
    
    /** Creates new form JFormConflictos */
    public JFormConflictos() {
        super(new Frame(), true);
        initComponents();
        
    }
    
    public void setDatos(JListaElementosConflictos poConflictos, JSincronizar poSincronizacion) throws Exception{
        moConflictos=poConflictos;
        moSincronizacion=poSincronizacion;
        
        rellenarPantalla();
        mostrarDatos();
    }
    private void rellenarPantalla() throws Exception {
    }
    private void mostrarDatos() throws Exception {
        moConsultaConflictos = new JCConflictos();
        moConsultaConflictos.setDatos(moConflictos, moSincronizacion.getParam().mbConflictosDefectoGanaCliente);
        moConsultaConflictos.refrescar(false,false);
        
        moModel = new JTableModel(moConsultaConflictos.moList);
        moModel.mbEditable=true;
        moModel.mbActualizarServidor=false;
        jTableCZ1.setModel(moModel);
        moModel.addMouseListenerToHeaderInTable(jTableCZ1);
        
        TableColumn loColumn = jTableCZ1.getColumnModel().getColumn(moConsultaConflictos.lPosiIndiceBase);
        ponerACerocolumna(loColumn);
        
    }
    private void ponerACerocolumna(TableColumn loColumn){
        loColumn.setWidth(0);
        loColumn.setPreferredWidth(0);
        loColumn.setMinWidth(0);
        loColumn.setMaxWidth(0);
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCZ1 = new utilesGUIx.JTableCZ();
        jPanel1 = new javax.swing.JPanel();
        btnProcesar = new utilesGUIx.JButtonCZ();
        btnCancelar = new utilesGUIx.JButtonCZ();
        btnDetallas = new utilesGUIx.JButtonCZ();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCZ1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCZ1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(this);
        jPanel1.add(btnProcesar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this);
        jPanel1.add(btnCancelar);

        btnDetallas.setText("Ver tabular");
        btnDetallas.addActionListener(this);
        jPanel1.add(btnDetallas);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnProcesar) {
            JFormConflictos.this.btnProcesarActionPerformed(evt);
        }
        else if (evt.getSource() == btnCancelar) {
            JFormConflictos.this.btnCancelarActionPerformed(evt);
        }
        else if (evt.getSource() == btnDetallas) {
            JFormConflictos.this.btnDetallasActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed

        try{
            moSincronizacion.resolverConflictosReal(moConsultaConflictos);
            dispose();
        }catch(Throwable e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e);
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        moSincronizacion.setCancelado(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDetallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallasActionPerformed
        try {
            moConsultaConflictos.moList.setIndex(jTableCZ1.getSelectedRow());
            JMostrarPantalla loMostrar = new JMostrarPantalla(null, JMostrarPantalla.mclEdicionFrame, JPanelGenerico.mclTipo);
            JPanelMostrarDiferencia loPanel = new JPanelMostrarDiferencia();
            loPanel.setDatos(moConsultaConflictos);
            loMostrar.mostrarEdicion(loPanel, loPanel);
        } catch (Exception ex) {
            utilesGUIx.msgbox.JMsgBox.mensajeErrorYLog(this, ex, getClass().getName());
        }



    }//GEN-LAST:event_btnDetallasActionPerformed
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnCancelar;
    private utilesGUIx.JButtonCZ btnDetallas;
    private utilesGUIx.JButtonCZ btnProcesar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private utilesGUIx.JTableCZ jTableCZ1;
    // End of variables declaration//GEN-END:variables
}
