/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelConexionesEDICION.java
 *
 * Created on 14-sep-2009, 19:34:51
 */

package utilesGUIx.configForm;

import utilesGUIx.Rectangulo;
import ListDatos.JSTabla;
import utiles.JDepuracion;
import utilesGUIx.JGUIxConfigGlobal;

import utilesGUIx.formsGenericos.edicion.JPanelGENERALBASE;

/**
 *
 * @author GONZE2
 */
public class JPanelConexionesEDICION  extends JPanelGENERALBASE {

    /** Creates new form JPanelConexionesEDICION */
    public JPanelConexionesEDICION() {
        initComponents();
        JGUIxConfigGlobal.getInstancia().setTextoTodosComponent(this);
    }

    public void setDatos(JConexion poConexion, JT2CONEXIONESModelo poConexiones) throws Exception{
        jPanelConexiones1.setDatos(poConexion, poConexiones);
    }
    public JSTabla getTabla() {
        return jPanelConexiones1.getTabla();
    }

    public void aceptar() throws Exception {
        jPanelConexiones1.aceptar();
    }
    public void cancelar() throws Exception {
        jPanelConexiones1.cancelar();
    }

    public void rellenarPantalla() throws Exception {
        jPanelConexiones1.rellenarPantalla();
    }

    public void mostrarDatos() throws Exception {
        jPanelConexiones1.mostrarDatos();
        txtNombre.setValueTabla(jPanelConexiones1.getConexion().getNombre());
    }

    public void establecerDatos() throws Exception {
        jPanelConexiones1.establecerDatos();
        jPanelConexiones1.getConexion().setNombre(txtNombre.getText());
    }

    public void habilitarSegunEdicion() throws Exception {
        jPanelConexiones1.habilitarSegunEdicion();
    }

    public void ponerTipoTextos() throws Exception {
        jPanelConexiones1.ponerTipoTextos();
    }

    public Rectangulo getTanano() {
        return jPanelConexiones1.getTanano();
    }

    public String getTitulo() {
        return jPanelConexiones1.getTitulo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        try {
            jPanelConexiones1 = new utilesGUIx.configForm.JPanelConexiones();
        } catch (java.lang.Exception e1) {
            e1.printStackTrace();
        }
        jPanel1 = new javax.swing.JPanel();
        btnPrueba = new utilesGUIx.JButtonCZ();
        jPanel2 = new javax.swing.JPanel();
        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        txtNombre = new utilesGUIx.JTextFieldCZ();

        setLayout(new java.awt.BorderLayout());
        add(jPanelConexiones1, java.awt.BorderLayout.CENTER);

        btnPrueba.setText("Probar");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrueba);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelCZ1.setText("Nombre de la conexión");
        jPanel2.add(jLabelCZ1, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(txtNombre, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
        try {
            jPanelConexiones1.probar();
            utilesGUIx.msgbox.JMsgBox.mensajeInformacion(jPanel1, "Prueba correcta");
        } catch (Exception ex) {
            JDepuracion.anadirTexto(getClass().getName(), ex);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, ex, true);
        }

    }//GEN-LAST:event_btnPruebaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnPrueba;
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private utilesGUIx.configForm.JPanelConexiones jPanelConexiones1;
    private utilesGUIx.JTextFieldCZ txtNombre;
    // End of variables declaration//GEN-END:variables

}
