/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utilesGUIxAvisos.forms;

import java.awt.Container;
import javax.swing.JMenuBar;
import utiles.JComunicacion;
import utilesGUIx.formsGenericos.edicion.JFormEdicionParametros;
import utilesGUIx.plugin.IPlugInFrame;
import utilesGUIx.plugin.swing.JPlugInFrameAbstract;
import utilesGUIxAvisos.calendario.JDatosGenerales;
import utilesGUIxAvisos.tablasExtend.JTEEGUIXEVENTOS;

/**
 *
 * @author eduardo
 */
public class JPanelOpcionesRepe extends JPlugInFrameAbstract {
    private JFormEdicionParametros moParametros = new JFormEdicionParametros();
    private JComunicacion moComu;
    private JDatosGenerales moDatosGenerales;

    /**
     * Creates new form JPanelOpcionesRepe
     */
    public JPanelOpcionesRepe() {
        initComponents();
    }

    public void setDatos(JDatosGenerales poDatosGenerales, JComunicacion poComu){
        moDatosGenerales=poDatosGenerales;
        moComu=poComu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnSoloEste = new utilesGUIx.JButtonCZ();
        btnSiguientes = new utilesGUIx.JButtonCZ();
        btnTodos = new utilesGUIx.JButtonCZ();

        setLayout(new java.awt.GridBagLayout());

        btnSoloEste.setText("Solo este evento");
        btnSoloEste.setToolTipText("El resto de eventos de la serie permanecen igual");
        btnSoloEste.setMaximumSize(new java.awt.Dimension(101, 40));
        btnSoloEste.setMinimumSize(new java.awt.Dimension(101, 40));
        btnSoloEste.setPreferredSize(new java.awt.Dimension(101, 40));
        btnSoloEste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoloEsteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(btnSoloEste, gridBagConstraints);

        btnSiguientes.setText("Este eventos y los eventos siguientes");
        btnSiguientes.setToolTipText("Se cambiaran este y todos los eventos siguientes");
        btnSiguientes.setMaximumSize(new java.awt.Dimension(101, 40));
        btnSiguientes.setMinimumSize(new java.awt.Dimension(101, 40));
        btnSiguientes.setPreferredSize(new java.awt.Dimension(101, 40));
        btnSiguientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(btnSiguientes, gridBagConstraints);

        btnTodos.setText("Todos los eventos");
        btnTodos.setToolTipText("Se cambian todos los eventos de la serie");
        btnTodos.setMaximumSize(new java.awt.Dimension(101, 40));
        btnTodos.setMinimumSize(new java.awt.Dimension(101, 40));
        btnTodos.setPreferredSize(new java.awt.Dimension(101, 40));
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(btnTodos, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoloEsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoloEsteActionPerformed

        moComu.moObjecto=String.valueOf(JTEEGUIXEVENTOS.mclSoloEste);
        moDatosGenerales.getMostrarPantalla().cerrarForm(this);
        
    }//GEN-LAST:event_btnSoloEsteActionPerformed

    private void btnSiguientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientesActionPerformed
        moComu.moObjecto=String.valueOf(JTEEGUIXEVENTOS.mclSiguientes);
        moDatosGenerales.getMostrarPantalla().cerrarForm(this);

    }//GEN-LAST:event_btnSiguientesActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        moComu.moObjecto=String.valueOf(JTEEGUIXEVENTOS.mclTodos);
        moDatosGenerales.getMostrarPantalla().cerrarForm(this);

    }//GEN-LAST:event_btnTodosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnSiguientes;
    private utilesGUIx.JButtonCZ btnSoloEste;
    private utilesGUIx.JButtonCZ btnTodos;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getIdentificador() {
        return this.getName();
    }

    @Override
    public JFormEdicionParametros getParametros() {
        return moParametros;
    }
}
