  /*
 * JPanelCargarCampos.java
 *
 * Created on 04 de enero de 2017
 *
 */
package utilesGUIxAvisos.forms;

import ListDatos.JSTabla;
import java.awt.Component;
import java.awt.Rectangle;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTextPane;
import utilesGUIx.JTextFieldCZ;
import utilesGUIx.Rectangulo;
import utilesGUIx.formsGenericos.edicion.JPanelGENERALBASE;

/**
 *
 * @author ricardo
 */
public class JPanelCargarCampos extends JPanelGENERALBASE {

    private Component moComponentFocused;
    private int mlCaretPosition;
    private HashMap<String, Object> moCampos;

    public JPanelCargarCampos() throws Exception {
        initComponents();
    }

    public void setDatos(HashMap<String, Object> poCampos, Component poComponentFocused, int plCaretPosition) throws Exception {
        moCampos = poCampos;
        moComponentFocused = poComponentFocused;
        mlCaretPosition = plCaretPosition;
    }

    @Override
    public JSTabla getTabla() {
        return null;
    }

    @Override
    public void rellenarPantalla() throws Exception {
        cmbCampos.borrarTodo();

        for(Map.Entry<String, Object> entry : moCampos.entrySet()) {
            String lsNombreCampo = entry.getKey();
            cmbCampos.addLinea(lsNombreCampo, lsNombreCampo);
        }
    }

    @Override
    public void habilitarSegunEdicion() throws Exception {
    }

    @Override
    public void mostrarDatos() throws Exception {
    }

    @Override
    public void establecerDatos() throws Exception {
    }

    @Override
    public void aceptar() throws Exception {
        String lsCampo = cmbCampos.getFilaActual().msCampo(0);
        if (moComponentFocused instanceof JTextFieldCZ) {
            JTextFieldCZ loText = (JTextFieldCZ) moComponentFocused;
            StringBuffer lsTexto = new StringBuffer(loText.getText());
            lsTexto.insert(mlCaretPosition, "[" + lsCampo + "]");
            loText.setText(lsTexto.toString());
        } else if (moComponentFocused instanceof JTextPane) {
            JTextPane loText = (JTextPane) moComponentFocused;
            loText.getDocument().insertString(mlCaretPosition, "[" + lsCampo + "]", null);
        }
    }

    @Override
    public void cancelar() throws Exception {
    }

    @Override
    public Rectangulo getTanano() {
        return new Rectangulo(0, 0, 450, 250);
    }

    @Override
    public String getTitulo() {
        return "Cargar campos";
    }

    @Override
    public boolean validarDatos() throws Exception {
        return super.validarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelAsignacionServicio = new javax.swing.JPanel();
        cmbCampos = new utilesGUIx.JComboBoxCZ();
        jLabelCZ2 = new utilesGUIx.JLabelCZ();

        setLayout(new java.awt.GridBagLayout());

        jPanelAsignacionServicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargar Campos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanelAsignacionServicio.setLayout(new java.awt.GridBagLayout());

        cmbCampos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 2);
        jPanelAsignacionServicio.add(cmbCampos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanelAsignacionServicio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabelCZ2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JComboBoxCZ cmbCampos;
    private utilesGUIx.JLabelCZ jLabelCZ2;
    private javax.swing.JPanel jPanelAsignacionServicio;
    // End of variables declaration//GEN-END:variables

}
