/*
 * JPanelBusqueda.java
 *
 * Created on 6 de septiembre de 2004, 12:07
 */
package utilesGUIxAvisos.forms;

import ListDatos.JFilaDatosDefecto;
import javax.swing.JPanel;
import utiles.IListaElementos;
import utiles.JDateEdu;
import utiles.JListaElementos;
import utilesGUIx.formsGenericos.IPanelControlador;
import utilesGUIx.formsGenericos.IPanelGenericoListener;
import utilesGUIx.formsGenericos.JPanelGeneralParametros;
import utilesGUIx.formsGenericos.JTablaConfig;
import utilesGUIx.msgbox.JMsgBox;
import utilesGUIxAvisos.tablasControladoras.JT2GUIXEVENTOS;

/**
 * representa una panel de búsqueda/principal, con posibilidades de filtros,
 * botones de edicón estandar y botones dinamicos personalizados
 */
public class JPanelGenericoEVENTOSMES extends JPanel implements utilesGUIx.formsGenericos.IPanelGenerico {

    private static final long serialVersionUID = 1L;
    private JDateEdu moDate;
    private boolean mbDesactivar = false;
    private JPanelGeneralParametros moParametros = new JPanelGeneralParametros();
    private IListaElementos moListaBotones = new JListaElementos();
    private IListaElementos moListeners = new JListaElementos();

    /**
     * Creates new form JPanelBusqueda
     */
    public JPanelGenericoEVENTOSMES() {
        super();
        initComponents();
        moDate = new JDateEdu();
        try {
            mbDesactivar = true;
            String[] lasMes = JDateEdu.masNombresMes();
            cmbMes.borrarTodo();
            for (int i = 0; i < lasMes.length; i++) {
                cmbMes.addLinea(lasMes[i], String.valueOf(i + 1) + JFilaDatosDefecto.mcsSeparacion1);
            }
        } finally {
            mbDesactivar = false;
        }
        mostrarDatos();

    }

    private void mostrarDatos() {
        try {
            mbDesactivar = true;
            cmbMes.setValueTabla(String.valueOf(moDate.getMes()) + JFilaDatosDefecto.mccSeparacion1);
            txtAno.setValueTabla(String.valueOf(moDate.getAno()));

        } finally {
            mbDesactivar = false;
        }
    }

    public void setControlador(JT2GUIXEVENTOS poControlador) throws Exception {
        jPanelMES1.setControlador(poControlador);
        refrescarDatos();
    }

    private void refrescarDatos() throws Exception {
        moDate.setAno(Integer.valueOf(txtAno.getText()).intValue());
        moDate.setMes(Integer.valueOf(cmbMes.getFilaActual().msCampo(0)).intValue());
        jPanelMES1.setMes(moDate.getAno(), moDate.getMes());

    }

    @Override
    public void seleccionarTodo() {
    }

    @Override
    public void seleccionarFila(int plFila, boolean pbSeleccionar) {
    }

    @Override
    public JTablaConfig getTablaConfig() {
        return null;
    }

    @Override
    public IListaElementos getBotones() {
        return moListaBotones;
    }

    @Override
    public JPanel getPanelInformacion() {
        return null;
    }

    @Override
    public void addListenerIPanelGenerico(IPanelGenericoListener poListener) {
        moListeners.add(poListener);
    }

    @Override
    public void removeListenerIPanelGenerico(IPanelGenericoListener poListener) {
        moListeners.remove(poListener);
    }

    @Override
    public int[] getSelectedRows() {
        return new int[0];
    }

    @Override
    public void refrescar() {
        try {
            jPanelMES1.refrescarDias();
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnAnterior = new utilesGUIx.JButtonCZ();
        cmbMes = new utilesGUIx.JComboBoxCZ();
        txtAno = new utilesGUIx.JTextFieldCZ();
        btnSiguiente = new utilesGUIx.JButtonCZ();
        jPanelMES1 = new utilesGUIxAvisos.forms.util.JPanelMES();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 20));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIxAvisos/images/Back16.gif"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel1.add(btnAnterior, gridBagConstraints);

        cmbMes.setFont(new java.awt.Font("Andale Mono", 1, 14)); // NOI18N
        cmbMes.setMinimumSize(new java.awt.Dimension(150, 24));
        cmbMes.setPreferredSize(new java.awt.Dimension(150, 24));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel1.add(cmbMes, gridBagConstraints);

        txtAno.setFont(new java.awt.Font("Andale Mono", 1, 14)); // NOI18N
        txtAno.setMinimumSize(new java.awt.Dimension(100, 19));
        txtAno.setPreferredSize(new java.awt.Dimension(100, 19));
        txtAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel1.add(txtAno, gridBagConstraints);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilesGUIxAvisos/images/Forward16.gif"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel1.add(btnSiguiente, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanelMES1.setBackground(new java.awt.Color(255, 255, 255));
        add(jPanelMES1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        if (!mbDesactivar) {
            try {
                refrescarDatos();
            } catch (Exception ex) {
                JMsgBox.mensajeError(this, ex);
            }
        }
    }//GEN-LAST:event_cmbMesItemStateChanged

    private void txtAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnoFocusLost
        if (!mbDesactivar) {
            try {
                refrescarDatos();
            } catch (Exception ex) {
                JMsgBox.mensajeError(this, ex);
            }
        }

    }//GEN-LAST:event_txtAnoFocusLost

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            moDate.add(JDateEdu.mclMes, -1);
            mostrarDatos();
            refrescarDatos();
        } catch (Exception ex) {
            JMsgBox.mensajeError(this, ex);
        }

    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            moDate.add(JDateEdu.mclMes, 1);
            mostrarDatos();
            refrescarDatos();
        } catch (Exception ex) {
            JMsgBox.mensajeError(this, ex);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnAnterior;
    private utilesGUIx.JButtonCZ btnSiguiente;
    private utilesGUIx.JComboBoxCZ cmbMes;
    private javax.swing.JPanel jPanel1;
    private utilesGUIxAvisos.forms.util.JPanelMES jPanelMES1;
    private utilesGUIx.JTextFieldCZ txtAno;
    // End of variables declaration//GEN-END:variables
}
