/*
 * JFormLogin.java
 *
 * Created on 7 de septiembre de 2004, 12:27
 */

package archivosPorWeb.cliente;


import archivosPorWeb.comun.JServidorArchivosWEBLogin;
import archivosPorWeb.comun.JServidorArchivosWeb;
import utiles.JDepuracion;
import utiles.config.ConfigurationParametersManager;
import utilesGUIx.JGUIxConfigGlobal;


public class JFormLogin extends javax.swing.JDialog {
    private static final String mcsUltUsuario = "UltUsuario";
    private static final String mcsUltTipoConexion = "UltTipoConexion";
    private static final long serialVersionUID = 1L;
    private JServidorArchivosWeb moServidorWeb;

    /** Creates new form JFormLogin */
    public JFormLogin(java.awt.Frame parent, boolean modal, JServidorArchivosWeb loServidorWeb) {
        super(parent, modal);
        initComponents();
        moServidorWeb = loServidorWeb;
        recargarCombo();
        JGUIxConfigGlobal.getInstancia().setTextoBoton(jButtonAceptar);
        JGUIxConfigGlobal.getInstancia().setTextoBoton(jButtonCancelar);
        jLabel1.setText(JGUIxConfigGlobal.getInstancia().getTextosForms().getTexto(jLabel1.getText()));
        jLabelCZ1.setText(JGUIxConfigGlobal.getInstancia().getTextosForms().getTexto(jLabelCZ1.getText()));
        jLabelCZ2.setText(JGUIxConfigGlobal.getInstancia().getTextosForms().getTexto(jLabelCZ2.getText()));

    }
    
    private void recargarCombo(){
        jTextLogin.setText(getUltUsuario());
        jTextDireccion.setText(JDatosGeneralesP.getDatosGenerales().getDireccionServidor());
    }
    
    private String getUltUsuario(){
        try{
            return ConfigurationParametersManager.getParametro(mcsUltUsuario);
        }catch(Exception e){
            return "";
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        jTextLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextPassWord = new javax.swing.JPasswordField();
        jLabelCZ2 = new utilesGUIx.JLabelCZ();
        jTextDireccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabelCZ1.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabelCZ1, gridBagConstraints);

        jTextLogin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jTextLogin, gridBagConstraints);

        jLabel1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabel1, gridBagConstraints);

        jTextPassWord.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jTextPassWord, gridBagConstraints);

        jLabelCZ2.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabelCZ2, gridBagConstraints);

        jTextDireccion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jTextDireccion, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(110, 25));
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(110, 25));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(357, 203));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
       try{
            try {
                ConfigurationParametersManager.setParametro(mcsUltUsuario, jTextLogin.getText());
                ConfigurationParametersManager.setParametro(JDatosGenerales.mcsDireccionServidor, jTextDireccion.getText());
                ConfigurationParametersManager.guardarPropiedades();
            } catch (Exception ex) {
                JDepuracion.anadirTexto(getClass().getName(), ex);
            }
            JServidorArchivosWEBLogin loLogin = new JServidorArchivosWEBLogin(
                    jTextLogin.getText(),jTextPassWord.getText());
            moServidorWeb.setURLBase1(jTextDireccion.getText());

            loLogin.setServidorInternet(moServidorWeb);
            if(!loLogin.autentificar()){
                throw new Exception("Login incorrecto");
            }
            dispose();
        }catch(Exception e){
            JDepuracion.anadirTexto(getClass().getName(), e);
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }


    }//GEN-LAST:event_jButtonAceptarActionPerformed



    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private utilesGUIx.JLabelCZ jLabelCZ2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JPasswordField jTextPassWord;
    // End of variables declaration//GEN-END:variables

    

}

