/*
 * JFormOpciones.java
 *
 * Created on 30 de agosto de 2007, 13:54
 */

package generadorClases.opciones;

/**
 *
 * @author  chema
 */
public class JFormOpciones extends javax.swing.JDialog {
    private JOpcionesGlobal moOpciones;
    
    /** Creates new form JFormOpciones */
    public JFormOpciones(java.awt.Frame parent, boolean modal, JOpcionesGlobal poOpciones) {
        super(parent, modal);
        initComponents();
        moOpciones = poOpciones;
        recuperarDatos();
    }
    
    private void recuperarDatos() {
        chkTabForm.setSelected(moOpciones.getIncluirTabForm());
        chkTabBorrarCascada.setSelected(moOpciones.getBorrarEnCascada());
        chkTabPKInvisibles.setSelected(moOpciones.getPKInvisibles());
        chkTabEdicionFX.setSelected(moOpciones.isEdicionFX());
        chkTablasExtends.setSelected(moOpciones.isUsarJTEE());
        txtCamposMinimosTodosModulos.setText(
                String.valueOf(moOpciones.getCamposMinimosTodosModulos())
                );
    }
    
    private void establecerDatos() {
        moOpciones.setIncluirTabForm(chkTabForm.isSelected());
        moOpciones.setBorrarEnCascada(chkTabBorrarCascada.isSelected());
        moOpciones.setPKInvisibles(chkTabPKInvisibles.isSelected());
        moOpciones.setEdicionFX(chkTabEdicionFX.isSelected());
        moOpciones.setUsarJTEE(chkTablasExtends.isSelected());
        moOpciones.setCamposMinimosTodosModulos(
                Integer.valueOf(txtCamposMinimosTodosModulos.getText()).intValue()
                );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        chkTabForm = new utilesGUIx.JCheckBoxCZ();
        chkTabBorrarCascada = new utilesGUIx.JCheckBoxCZ();
        chkTabEdicionFX = new utilesGUIx.JCheckBoxCZ();
        chkTabPKInvisibles = new utilesGUIx.JCheckBoxCZ();
        chkTablasExtends = new utilesGUIx.JCheckBoxCZ();
        jLabelCZ1 = new utilesGUIx.JLabelCZ();
        txtCamposMinimosTodosModulos = new utilesGUIx.JTextFieldCZ();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new utilesGUIx.JButtonCZ();
        btnCancelar = new utilesGUIx.JButtonCZ();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones Generales");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        chkTabForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkTabForm.setText("¿Formularios con Tab por defecto?");
        chkTabForm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(chkTabForm, gridBagConstraints);

        chkTabBorrarCascada.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkTabBorrarCascada.setText("Permitir borrados en cascada");
        chkTabBorrarCascada.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(chkTabBorrarCascada, gridBagConstraints);

        chkTabEdicionFX.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkTabEdicionFX.setText("Formularios en JAVA FX");
        chkTabEdicionFX.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(chkTabEdicionFX, gridBagConstraints);

        chkTabPKInvisibles.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkTabPKInvisibles.setText("Claves primarias invisibles");
        chkTabPKInvisibles.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(chkTabPKInvisibles, gridBagConstraints);

        chkTablasExtends.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkTablasExtends.setText("usar tablas JTEETabla  en vez de JTTabla2");
        chkTablasExtends.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(chkTablasExtends, gridBagConstraints);

        jLabelCZ1.setText("Campos mínimos para generar el JPanel, Controlador, y JTFORMConsulta");
        getContentPane().add(jLabelCZ1, new java.awt.GridBagConstraints());

        txtCamposMinimosTodosModulos.setTipo(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtCamposMinimosTodosModulos, gridBagConstraints);

        jPanel1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel1, gridBagConstraints);

        btnAceptar.setText("aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(jPanel2, gridBagConstraints);

        setSize(new java.awt.Dimension(646, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        establecerDatos();
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JButtonCZ btnAceptar;
    private utilesGUIx.JButtonCZ btnCancelar;
    private utilesGUIx.JCheckBoxCZ chkTabBorrarCascada;
    private utilesGUIx.JCheckBoxCZ chkTabEdicionFX;
    private utilesGUIx.JCheckBoxCZ chkTabForm;
    private utilesGUIx.JCheckBoxCZ chkTabPKInvisibles;
    private utilesGUIx.JCheckBoxCZ chkTablasExtends;
    private utilesGUIx.JLabelCZ jLabelCZ1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private utilesGUIx.JTextFieldCZ txtCamposMinimosTodosModulos;
    // End of variables declaration//GEN-END:variables
    
}
