/*
 * JGraficoFormPropiedades.java
 *
 * Created on 4 de enero de 2006, 14:12
 */

package generadorGraficosXY;

import java.awt.Frame;
import utilesGUI.tiposTextos.ITipoTexto;
import utilesGUI.tiposTextos.JTipoTextoEstandar;

public class JGraficoFormPropiedades extends java.awt.Dialog {
    JGraficoPropiedades moProp;
    /** Creates new form JGraficoFormPropiedades */
    public JGraficoFormPropiedades(Frame poFrame, JGraficoPropiedades poProp) {
        super(poFrame, true);
        initComponents();
        setTitle("Propiedades");
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-441)/2, (screenSize.height-440)/2, 441, 440);
        moProp = poProp;
        ponerTiposTextos();
        mostrarDatos();
    }
    
    private void ponerTiposTextos(){
        txtTituloPrincipio.setTipo(JTipoTextoEstandar.mclTextCadena);
        txtXEtiqEje.setTipo(JTipoTextoEstandar.mclTextCadena);
        txtXFechaMin.setTipo(JTipoTextoEstandar.mclTextFecha);
        txtXFormatoFecha.setTipo(JTipoTextoEstandar.mclTextCadena);
        txtXIntervalo.setTipo(JTipoTextoEstandar.mclTextNumeroDoble);
        txtYEtiqEje.setTipo(JTipoTextoEstandar.mclTextCadena);
        txtYIntervalo.setTipo(JTipoTextoEstandar.mclTextNumeroDoble);
        txtYValorMin.setTipo(JTipoTextoEstandar.mclTextNumeroDoble);
    }
    private void mostrarDatos(){
        txtTituloPrincipio.setValueTabla(moProp.msTituloPrincipio);
        txtXEtiqEje.setValueTabla(moProp.msXEtiqEje);
        txtXFechaMin.setValueTabla(moProp.msXFechaMin);
        txtXFormatoFecha.setValueTabla(moProp.msXFormatoFecha);
        txtXIntervalo.setValueTabla(moProp.msXIntervalo);
        txtYEtiqEje.setValueTabla(moProp.msYEtiqEje);
        txtYIntervalo.setValueTabla(moProp.msYIntervalo);
        txtYValorMin.setValueTabla(moProp.msYValorMin);
        
        ColorSerie.setColor(moProp.moColorSerie);
        
        chkVisibleLeyenda.setValueTabla(new Boolean(moProp.mbVisibleLeyenda));
        chkXDivisiones.setValueTabla(new Boolean(moProp.mbXDivisiones));
        chkYDivisiones.setValueTabla(new Boolean(moProp.mbYDivisiones));
        
    }
    private void establecerDatos(){
        moProp.msTituloPrincipio = txtTituloPrincipio.getText();
        moProp.msXEtiqEje = txtXEtiqEje.getText();
        moProp.msXFechaMin = txtXFechaMin.getText();
        moProp.msXFormatoFecha = txtXFormatoFecha.getText();
        moProp.msXIntervalo = txtXIntervalo.getText();
        moProp.msYEtiqEje = txtYEtiqEje.getText();
        moProp.msYIntervalo = txtYIntervalo.getText();
        moProp.msYValorMin = txtYValorMin.getText();

        moProp.moColorSerie = ColorSerie.getColor();
        
        moProp.mbVisibleLeyenda = chkVisibleLeyenda.getState();
        moProp.mbXDivisiones = chkXDivisiones.getState();
        moProp.mbYDivisiones = chkYDivisiones.getState();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label12 = new java.awt.Label();
        label1 = new java.awt.Label();
        txtTituloPrincipio = new utilesGUI.TextFieldCZ();
        label2 = new java.awt.Label();
        ColorSerie = new utilesGUI.ColorSeleccion();
        chkVisibleLeyenda = new utilesGUI.CheckBoxCZ();
        label10 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        label3 = new java.awt.Label();
        txtXEtiqEje = new utilesGUI.TextFieldCZ();
        chkXDivisiones = new utilesGUI.CheckBoxCZ();
        label6 = new java.awt.Label();
        txtXFechaMin = new utilesGUI.TextFieldCZ();
        label7 = new java.awt.Label();
        txtXIntervalo = new utilesGUI.TextFieldCZ();
        label5 = new java.awt.Label();
        txtXFormatoFecha = new utilesGUI.TextFieldCZ();
        label11 = new java.awt.Label();
        panel2 = new java.awt.Panel();
        label4 = new java.awt.Label();
        txtYEtiqEje = new utilesGUI.TextFieldCZ();
        chkYDivisiones = new utilesGUI.CheckBoxCZ();
        label8 = new java.awt.Label();
        txtYValorMin = new utilesGUI.TextFieldCZ();
        label9 = new java.awt.Label();
        txtYIntervalo = new utilesGUI.TextFieldCZ();
        panel3 = new java.awt.Panel();
        btnAceptar = new java.awt.Button();
        btnCancelar = new java.awt.Button();

        setLayout(new java.awt.GridBagLayout());

        setBackground(new java.awt.Color(225, 231, 228));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setBackground(new java.awt.Color(48, 111, 150));
        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Generales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(label12, gridBagConstraints);

        label1.setText("T\u00edtulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(label1, gridBagConstraints);

        txtTituloPrincipio.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(txtTituloPrincipio, gridBagConstraints);

        label2.setText("Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(label2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(ColorSerie, gridBagConstraints);

        chkVisibleLeyenda.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        chkVisibleLeyenda.setLabel("Visible leyenda?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(chkVisibleLeyenda, gridBagConstraints);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(new java.awt.Color(48, 111, 150));
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Eje X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(label10, gridBagConstraints);

        panel1.setLayout(new java.awt.GridBagLayout());

        label3.setText("T\u00edtulo eje X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(label3, gridBagConstraints);

        txtXEtiqEje.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(txtXEtiqEje, gridBagConstraints);

        chkXDivisiones.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        chkXDivisiones.setLabel("Divisiones X?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(chkXDivisiones, gridBagConstraints);

        label6.setText("X Fecha M\u00ednima");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(label6, gridBagConstraints);

        txtXFechaMin.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(txtXFechaMin, gridBagConstraints);

        label7.setText("X Intervalo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(label7, gridBagConstraints);

        txtXIntervalo.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(txtXIntervalo, gridBagConstraints);

        label5.setText("Formato fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(label5, gridBagConstraints);

        txtXFormatoFecha.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel1.add(txtXFormatoFecha, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(panel1, gridBagConstraints);

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setBackground(new java.awt.Color(48, 111, 150));
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Eje Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(label11, gridBagConstraints);

        panel2.setLayout(new java.awt.GridBagLayout());

        label4.setText("T\u00edtulo eje Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(label4, gridBagConstraints);

        txtYEtiqEje.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(txtYEtiqEje, gridBagConstraints);

        chkYDivisiones.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        chkYDivisiones.setLabel("Divisiones Y?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(chkYDivisiones, gridBagConstraints);

        label8.setText("Y Valor M\u00ednimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(label8, gridBagConstraints);

        txtYValorMin.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(txtYValorMin, gridBagConstraints);

        label9.setText("Y Intervalo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(label9, gridBagConstraints);

        txtYIntervalo.setBackColorConFoco(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        panel2.add(txtYIntervalo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(panel2, gridBagConstraints);

        panel3.setBackground(new java.awt.Color(48, 111, 150));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setLabel("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        panel3.add(btnAceptar);

        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        panel3.add(btnCancelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(panel3, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-441)/2, (screenSize.height-324)/2, 441, 324);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try{
            establecerDatos();
            dispose();
        }catch(Exception e){
            e.printStackTrace();
            utilesGUI.msgbox.JDialogo.showDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUI.ColorSeleccion ColorSerie;
    private java.awt.Button btnAceptar;
    private java.awt.Button btnCancelar;
    private utilesGUI.CheckBoxCZ chkVisibleLeyenda;
    private utilesGUI.CheckBoxCZ chkXDivisiones;
    private utilesGUI.CheckBoxCZ chkYDivisiones;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private utilesGUI.TextFieldCZ txtTituloPrincipio;
    private utilesGUI.TextFieldCZ txtXEtiqEje;
    private utilesGUI.TextFieldCZ txtXFechaMin;
    private utilesGUI.TextFieldCZ txtXFormatoFecha;
    private utilesGUI.TextFieldCZ txtXIntervalo;
    private utilesGUI.TextFieldCZ txtYEtiqEje;
    private utilesGUI.TextFieldCZ txtYIntervalo;
    private utilesGUI.TextFieldCZ txtYValorMin;
    // End of variables declaration//GEN-END:variables
    
}
