/*
 * JGraficoForm.java
 *
 * Created on 4 de enero de 2006, 8:48
 */

package generadorGraficosXY;

import java.sql.Connection;

public class JGraficoForm extends java.awt.Frame {
    
    /** Creates new form JGraficoForm */
    public JGraficoForm() {
        initComponents();
    }
    
    public void crearConexion(Connection poConex) throws Exception {
        jGraficoPanelGenerador1.crearConexion(poConex);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGraficoPanelGenerador1 = new generadorGraficosXY.JGraficoPanelGenerador();
        menuBar1 = new java.awt.MenuBar();
        menuArchivo = new java.awt.Menu();
        mnuAConexion = new java.awt.MenuItem();
        mnuASalir = new java.awt.MenuItem();
        menuGrafico = new java.awt.Menu();
        mnuGPropiedadesGenerales = new java.awt.MenuItem();
        mnuGPropiedades = new java.awt.MenuItem();
        mnuGRefrescar = new java.awt.MenuItem();
        menuAyuda = new java.awt.Menu();
        menuAyAyuda = new java.awt.MenuItem();

        setTitle("Generador de gráficos XY");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        add(jGraficoPanelGenerador1, java.awt.BorderLayout.CENTER);

        menuArchivo.setLabel("Archivo");

        mnuAConexion.setLabel("Conexión");
        mnuAConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAConexionActionPerformed(evt);
            }
        });
        menuArchivo.add(mnuAConexion);
        menuArchivo.addSeparator();
        mnuASalir.setLabel("Salir");
        mnuASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuASalirActionPerformed(evt);
            }
        });
        menuArchivo.add(mnuASalir);

        menuBar1.add(menuArchivo);

        menuGrafico.setLabel("Gráfico");

        mnuGPropiedadesGenerales.setLabel("Propiedades para todos los gráficos");
        menuGrafico.add(mnuGPropiedadesGenerales);

        mnuGPropiedades.setLabel("Propiedades gráfico actual");
        menuGrafico.add(mnuGPropiedades);
        menuGrafico.addSeparator();
        mnuGRefrescar.setLabel("Refrescar gráfico");
        mnuGRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGRefrescarActionPerformed(evt);
            }
        });
        menuGrafico.add(mnuGRefrescar);

        menuBar1.add(menuGrafico);

        menuAyuda.setLabel("Ayuda");

        menuAyAyuda.setLabel("Ayuda");
        menuAyAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyAyudaActionPerformed(evt);
            }
        });
        menuAyuda.add(menuAyAyuda);

        menuBar1.add(menuAyuda);

        setMenuBar(menuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-635)/2, (screenSize.height-389)/2, 635, 389);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAyAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyAyudaActionPerformed

        JGraficoAyuda loForm = new JGraficoAyuda();
        loForm.show();
        
    }//GEN-LAST:event_menuAyAyudaActionPerformed

    private void mnuGRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGRefrescarActionPerformed
        try{
            jGraficoPanelGenerador1.refrescar();
        }catch(Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }

    }//GEN-LAST:event_mnuGRefrescarActionPerformed

    private void mnuASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuASalirActionPerformed
        dispose();
    }//GEN-LAST:event_mnuASalirActionPerformed

    private void mnuAConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAConexionActionPerformed
        try{
            JGraficoFormConexion loForm = new JGraficoFormConexion(this, true, this);
            loForm.setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
        
    }//GEN-LAST:event_mnuAConexionActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JGraficoForm().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private generadorGraficosXY.JGraficoPanelGenerador jGraficoPanelGenerador1;
    private java.awt.Menu menuArchivo;
    private java.awt.MenuItem menuAyAyuda;
    private java.awt.Menu menuAyuda;
    private java.awt.MenuBar menuBar1;
    private java.awt.Menu menuGrafico;
    private java.awt.MenuItem mnuAConexion;
    private java.awt.MenuItem mnuASalir;
    private java.awt.MenuItem mnuGPropiedades;
    private java.awt.MenuItem mnuGPropiedadesGenerales;
    private java.awt.MenuItem mnuGRefrescar;
    // End of variables declaration//GEN-END:variables
    
}
