/*
 * JPanelGeneradorGraficosXY.java
 *
 * Created on 3 de enero de 2006, 18:31
 */

package generadorGraficosXY;


import java.sql.Connection;
import java.awt.image.*;
import javax.imageio.*;

import utilesGUI.grafxy2.*;

public class JGraficoPanelGenerador extends java.awt.Panel {
    JGraficos moGraficos = new JGraficos();
    int lIndex = 0;
    
    /** Creates new form JPanelGeneradorGraficosXY */
    public JGraficoPanelGenerador() {
        initComponents();
    }
    
    public void refrescar() throws Exception {
        JGrafico loGraf =  (JGrafico)moGraficos.moGraficos.get(lIndex);
        loGraf.refrescarGraf(moGraficos, jGraf21);
    }
    
    public boolean anterior(){
        boolean lbExito = true;
        lIndex--;
        if(lIndex<0){
            lIndex=0;
            lbExito = false;
        }
        return lbExito;
    }
    public boolean siguiente(){
        boolean lbExito = true;
        lIndex++;
        if(lIndex>=moGraficos.moGraficos.size()){
            lIndex--;
            lbExito = false;
        }
        return lbExito;
    }
    
    public void guardarActual(String psFichero, String psExt) throws Exception {

        refrescar();
        
        BufferedImage loImg = new BufferedImage(jGraf21.getBounds().width, jGraf21.getBounds().height, BufferedImage.TYPE_INT_RGB);
        jGraf21.paint(loImg.getGraphics());
        
        java.io.File loFile =new java.io.File(psFichero);
        loFile.delete();
        ImageIO.write(loImg, psExt, loFile);

    }
    
    public void guardarTodos(String psPath) throws Exception {
        lIndex = 0;
        do{
            guardarActual(psPath + getNombreBueno(((JGrafico)moGraficos.moGraficos.get(lIndex)).msCodigo) + ".png", "png");
        }while(siguiente());
    }
    
    
    public void crearConexion(Connection poConex) throws Exception {
        moGraficos.refrescarDatos(poConex);
        lIndex=0;
        refrescar();
    }
    
    private String getNombreBueno(final String psNombre){
        StringBuffer loBuffer = new StringBuffer();
        for(int i = 0 ; i < psNombre.length() ; i++){
            if((psNombre.charAt(i)>='0' && psNombre.charAt(i) <='9') ||
               (psNombre.charAt(i)>='a' && psNombre.charAt(i) <='z') ||
               (psNombre.charAt(i)>='A' && psNombre.charAt(i) <='Z')){
                loBuffer.append(psNombre.charAt(i));
            }
        }
        return loBuffer.toString().substring(0,15);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGraf21 = new utilesGUI.grafxy2.JGraf2();
        panel1 = new java.awt.Panel();
        btnAtras = new java.awt.Button();
        btnSiguiente = new java.awt.Button();
        label4 = new java.awt.Label();
        btnRefrescar = new java.awt.Button();
        label1 = new java.awt.Label();
        btnPropiedadesGenerales = new java.awt.Button();
        btnPropiedades = new java.awt.Button();
        label3 = new java.awt.Label();
        btnGuardarTodos = new java.awt.Button();
        btnGuardar = new java.awt.Button();

        setLayout(new java.awt.BorderLayout());

        add(jGraf21, java.awt.BorderLayout.CENTER);

        panel1.setLayout(new java.awt.GridBagLayout());

        btnAtras.setLabel("Anterior");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        panel1.add(btnAtras, new java.awt.GridBagConstraints());

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        panel1.add(btnSiguiente, new java.awt.GridBagConstraints());

        label4.setText(" ");
        panel1.add(label4, new java.awt.GridBagConstraints());

        btnRefrescar.setLabel("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        panel1.add(btnRefrescar, new java.awt.GridBagConstraints());

        label1.setText(" ");
        panel1.add(label1, new java.awt.GridBagConstraints());

        btnPropiedadesGenerales.setLabel("Propied. Gen.");
        btnPropiedadesGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedadesGeneralesActionPerformed(evt);
            }
        });

        panel1.add(btnPropiedadesGenerales, new java.awt.GridBagConstraints());

        btnPropiedades.setLabel("Propiedades 1");
        btnPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedadesActionPerformed(evt);
            }
        });

        panel1.add(btnPropiedades, new java.awt.GridBagConstraints());

        label3.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panel1.add(label3, gridBagConstraints);

        btnGuardarTodos.setLabel("Guardar todos");
        btnGuardarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTodosActionPerformed(evt);
            }
        });

        panel1.add(btnGuardarTodos, new java.awt.GridBagConstraints());

        btnGuardar.setLabel("Guardar 1");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        panel1.add(btnGuardar, new java.awt.GridBagConstraints());

        add(panel1, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents

    private void btnPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedadesActionPerformed

        try{
            JGrafico loGraf =  (JGrafico)moGraficos.moGraficos.get(lIndex);
            if(loGraf.moPropiedades==null){
                loGraf.moPropiedades=moGraficos.moPropiedades.Clone();
            }
            JGraficoFormPropiedades loForm = new JGraficoFormPropiedades(new java.awt.Frame(), loGraf.moPropiedades);
            loForm.show();
            refrescar();
        }catch (Exception e){
            e.printStackTrace();
            utilesGUI.msgbox.JDialogo.showDialog(this, e.toString());
        }
        
        
    }//GEN-LAST:event_btnPropiedadesActionPerformed

    private void btnPropiedadesGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedadesGeneralesActionPerformed
        try{
            JGraficoFormPropiedades loForm = new JGraficoFormPropiedades(new java.awt.Frame(), moGraficos.moPropiedades);
            loForm.show();
            refrescar();
        }catch (Exception e){
            e.printStackTrace();
            utilesGUI.msgbox.JDialogo.showDialog(this, e.toString());
        }
               
    }//GEN-LAST:event_btnPropiedadesGeneralesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            java.awt.FileDialog loDialog = new java.awt.FileDialog(new java.awt.Frame());
            loDialog.setMode(loDialog.SAVE);
            loDialog.show();
            
            guardarActual(loDialog.getDirectory() + getNombreBueno(((JGrafico)moGraficos.moGraficos.get(lIndex)).msCodigo) + ".png", "png");
            
        }catch(Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTodosActionPerformed
        try{
            java.awt.FileDialog loDialog = new java.awt.FileDialog(new java.awt.Frame());
            loDialog.setMode(loDialog.SAVE);
            loDialog.show();
            
            guardarTodos(loDialog.getDirectory());
            
        }catch(Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
    }//GEN-LAST:event_btnGuardarTodosActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        try{
            refrescar();
        }catch (Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }

    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try{
            siguiente();
            refrescar();
        }catch (Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        try{
            anterior();
            refrescar();
        }catch (Exception e){
            e.printStackTrace();
            utilesGUIx.msgbox.JMsgBox.mensajeError(this, e.toString());
        }

    }//GEN-LAST:event_btnAtrasActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAtras;
    private java.awt.Button btnGuardar;
    private java.awt.Button btnGuardarTodos;
    private java.awt.Button btnPropiedades;
    private java.awt.Button btnPropiedadesGenerales;
    private java.awt.Button btnRefrescar;
    private java.awt.Button btnSiguiente;
    private utilesGUI.grafxy2.JGraf2 jGraf21;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
    
}
