/*
 * JVISTAPRELIMINAR.java
 *
 * Created on 20 de febrero de 2007, 10:46
 */

package utilesGUIx.imgTrata;

import ListDatos.JFilaDatosDefecto;
import java.awt.*;
import java.util.EventObject;
import javax.swing.ImageIcon;
import utiles.JConversiones;
import utiles.JDepuracion;

public class JVISTAPRELIMINAR extends javax.swing.JFrame implements IZoomCambioListener {
    private final JPanelVistaPrevia jPanelVistaPrevia1 = new JPanelVistaPrevia();
    
    /** Creates new form JVISTAPRELIMINAR */
    public JVISTAPRELIMINAR() {
        super();
        initComponents();

        if(utilesGUIx.JGUIxConfigGlobal.getInstancia().getMostrarPantalla().getImagenIcono()!=null){
            try{
                this.setIconImage(((ImageIcon) utilesGUIx.JGUIxConfigGlobal.getInstancia().getMostrarPantalla().getImagenIcono()).getImage());
            }catch(Throwable e){JDepuracion.anadirTexto(this.getClass().getName(), e);}
        }        
        setState(Frame.MAXIMIZED_BOTH);
        getContentPane().add(jPanelVistaPrevia1, BorderLayout.CENTER);
        jPanelVistaPrevia1.addZoomCambioListener(this);
        
        final Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, (screenSize.width), (screenSize.height-30));
        enableEvents(AWTEvent.MOUSE_EVENT_MASK);
        setState(Frame.MAXIMIZED_BOTH);
        
        cmbZoom.borrarTodo();
        cmbZoom.addLinea("","1.00001" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("25%","0.25" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("50%","0.5" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("100%","1" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("200%","2" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("300%","3" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("400%","4" + JFilaDatosDefecto.mcsSeparacion1);
        cmbZoom.addLinea("500%","5" + JFilaDatosDefecto.mcsSeparacion1);
//        cmbZoom.mbSeleccionarClave("1.00001" + JFilaDatosDefecto.mcsSeparacion1);
        
    }
    public void setImagen(final Image poImagen, final String psDescripcion) throws Exception {
        setVisible(true);
        jPanelVistaPrevia1.setVisible(true);
        jPanelVistaPrevia1.setImagen(poImagen);
        lblDescripcion.setText(psDescripcion);

//        System.gc();
        try{
            JDepuracion.anadirTexto(
                JDepuracion.mclINFORMACION,
                getClass().getName(),
                "Memoria libre " + String.valueOf(Runtime.getRuntime().freeMemory())
                );
        }catch(Throwable e){}
    }
    public void setImagen(final String psImagen, final String psDescripcion) throws Exception {
        setVisible(true);
        jPanelVistaPrevia1.setVisible(true);
        jPanelVistaPrevia1.setImagen(psImagen);
        lblDescripcion.setText(psDescripcion);
        
//        System.gc();
        try{
            JDepuracion.anadirTexto(
                JDepuracion.mclINFORMACION,
                getClass().getName(),
                "Memoria libre " + String.valueOf(Runtime.getRuntime().freeMemory())
                );
        }catch(Throwable e){}
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        cmbZoom = new utilesGUIx.JComboBoxCZ();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblDescripcion.setFont(new java.awt.Font("Dialog", 1, 18));
        lblDescripcion.setText(" ");
        lblDescripcion.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblDescripcion, gridBagConstraints);

        cmbZoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbZoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbZoomItemStateChanged(evt);
            }
        });

        jPanel1.add(cmbZoom, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbZoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbZoomItemStateChanged
        try{
            jPanelVistaPrevia1.setZoom(Double.valueOf(cmbZoom.getFilaActual().msCampo(0)).doubleValue());
        }catch(Exception e){
            
        }
                
    }//GEN-LAST:event_cmbZoomItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jPanelVistaPrevia1.stop();
        dispose();

    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    public void zoomCambio(EventObject poEvento) {
        if(JConversiones.mlComparaDoubles(
                JConversiones.cdbl(cmbZoom.getFilaActual().msCampo(0)) ,
                jPanelVistaPrevia1.getZoom(), 0.001 ) != 0 ) {
             cmbZoom.mbSeleccionarClave(String.valueOf(jPanelVistaPrevia1.getZoom()) + JFilaDatosDefecto.mcsSeparacion1);
        }
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilesGUIx.JComboBoxCZ cmbZoom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    // End of variables declaration//GEN-END:variables
    
}
